"""Embed data into a self-contained, offline HTML calculator and 3D viewer."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
data=json.loads((ROOT/'results.json').read_text())
layouts=[json.loads((ROOT/f).read_text()) for f in ['layout.json','layout-vw-inspired.json']]
template=r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ЗАЗ-968М • Паровой привод</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0b1421;color:#e5eef9;font:16px/1.5 system-ui,sans-serif}header,main{max-width:1450px;margin:auto;padding:28px}header{padding-bottom:12px}h1{font-size:34px;margin:8px 0}h2{font-size:23px;margin:0 0 18px}p{color:#aec0d8}a{color:#79b9ff}nav{display:flex;gap:16px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:20px}.card{background:#132236;border:1px solid #2b3b50;border-radius:16px;padding:22px;margin-bottom:20px}canvas{width:100%;height:540px;display:block;touch-action:none;background:#0b1421;border-radius:12px}label{display:block;margin:12px 0 6px}input,select,button{font:inherit;padding:8px;background:#0a1628;color:#e5eef9;border:1px solid #425672;border-radius:7px}input[type=range]{width:100%;padding:0;accent-color:#60a5fa}button{cursor:pointer}button:hover{background:#25425d}.row{display:flex;gap:12px;flex-wrap:wrap}.metric{padding:14px;background:#0d1a2c;border-radius:10px;flex:1;min-width:135px}.metric strong{display:block;font-size:27px}.note{border-left:3px solid #f59e0b;padding-left:14px;color:#d4c4a9}.warn{color:#fca5a5}.legend{display:flex;gap:12px;flex-wrap:wrap;font-size:14px;margin-top:14px}.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px}.small{font-size:13px;color:#a2b4cc}.coord{width:110px}#mass{width:160px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border-bottom:1px solid #34465d;padding:10px;text-align:left}.scroll{overflow-x:auto}@media(max-width:950px){.grid{grid-template-columns:1fr}canvas{height:400px}h1{font-size:27px}}@media print{canvas,.edit{display:none}body{background:white;color:black}.card{background:white}}
</style></head><body><header><div class="small">ИНЖЕНЕРНЫЙ ЭСКИЗ • 08.10.2026</div><h1>ЗАЗ-968М с паровым приводом</h1><p>Три расчетных режима, две архитектуры компоновки, чертежи и воспроизводимые расчеты.</p><nav><a href="report.html">Подробный отчет</a><a href="report.pdf">Отчет PDF</a><a href="drawings/01-layout.pdf">Компоновка</a><a href="drawings/02-process.pdf">Контур</a><a href="drawings/03-controls.pdf">Управление</a><a href="drawings/04-dashboard.pdf">Приборная панель</a><a href="drawings/05-vw-inspired.pdf">Вариант по примеру VW</a><a href="assembly.scad">CAD SCAD</a></nav><p class="note">Посадка реальных агрегатов, прочность, охлаждение и дорожный допуск пока не подтверждены. Бюджеты — авторские диапазоны планирования НИОКР. Внутренние размеры кузова и агрегатов в модели условные.</p></header><main>
<div class="grid"><section class="card"><h2>3D-компоновка • целевые габариты</h2><div class="row edit"><select id="layoutChoice" aria-label="Выбор компоновки"><option value="0">Генератор в моторном отсеке</option><option value="1">По примеру MSS VW: вместо заднего сиденья</option></select><button id="reset">Восстановить исходный эскиз</button><button id="top">Вид сверху</button><button id="side">Вид сбоку</button><button id="iso">Изометрия</button></div><p class="small">Перетаскивайте мышью для вращения; колесо — масштаб. Серый контур — наружная оболочка, розовый — условная зона салона.</p><canvas id="view" aria-label="Вращаемая 3D модель компоновки"></canvas><div id="legend" class="legend"></div><p id="layoutStatus" class="small"></p></section>
<aside class="card edit"><h2>Положение агрегата</h2><label for="part">Агрегат</label><select id="part"></select><div id="coords"></div><p id="partInfo" class="small"></p><button id="export">Сохранить измененный layout.json</button><h3>Проверка габаритов</h3><div id="collisions"></div><p class="small">Проверяются только AABB агрегатов и условная зона салона. Зазор 100 мм — фильтр, не норматив. Массы, трубы, тепловые зоны и подвеска при перемещении не пересчитываются.</p></aside></div>
<section class="card"><h2>Расчет мощности и расхода</h2><div class="grid"><div><label for="scenario">Сценарий</label><select id="scenario"><option value="0">A • 8 кВт / 6 бар abs / 200 °C</option><option value="1" selected>B • 18 кВт / 10 бар abs / 250 °C</option><option value="2">C • 29,42 кВт / 20 бар abs / 300 °C</option></select><label for="speed">Скорость: <b id="speedLabel"></b> км/ч</label><input id="speed" type="range" min="10" max="120" value="80"><label for="grade">Подъем: <b id="gradeLabel"></b>%</label><input id="grade" type="range" min="0" max="10" step="0.5" value="0"><label for="mass">Масса для дорожного расчета, кг</label><input id="mass" type="number" min="700" max="1600" value="1145"><p class="small">Расчет установившегося движения без ветра и прогрева. КПД считаются постоянными. Свойства пара предвычислены Python/CoolProp; интерактивная модель масштабирует тот же линейный баланс при фиксированных состояниях. Давления не являются уставками защиты.</p></div><div><div class="row" id="metrics"></div><p id="powerStatus" class="warn"></p><p id="rangeInfo"></p><p id="budget"></p></div></div></section>
<section class="card"><h2>Результаты при полной нагрузке</h2><div class="scroll"><table id="summary"></table></div><p class="note">C превышает условную полную массу 1200 кг. Во всех вариантах целевой конденсатор в 3D не подтвержден тепловым расчетом изготовителя. Низкая мощность при низком КПД может потребовать большего генератора.</p></section>
<section class="card"><h2>Как устроен VW из указанного ролика</h2><p>Оригинальный <a href="https://www.youtube.com/watch?v=Y-ywYzSoVDk">обзор Steve Lehto</a> и <a href="https://wiki.opensourceecology.org/wiki/Steam_Engine/Correspondence">письмо владельца Tom Kimmel</a> помогают отделить наблюдаемые узлы от неизвестных параметров. В отчете добавлено сравнение с проектом ЗАЗ и отмечено, что историческая регистрация автомобиля в США не подтверждает современный допуск в Финляндии или России.</p><p class="small">Вторая 3D-компоновка — новое предложение для ЗАЗ по принципу размещения агрегатов; размеры исторического VW не восстановлены. Ее теплообменник, масса и защитная перегородка требуют отдельного проекта.</p></section>
</main><script>
const DATA=__DATA__, ORIGINAL=__LAYOUTS__;let layout=structuredClone(ORIGINAL[0]);const el=id=>document.getElementById(id);let yaw=-0.55,pitch=0.65,zoom=1;
const canvas=el('view'),ctx=canvas.getContext('2d');let drag=null;
const verts=p=>{let [x,y,z]=p.xyz,[a,b,c]=p.size;return [[x,y,z],[x+a,y,z],[x+a,y+b,z],[x,y+b,z],[x,y,z+c],[x+a,y,z+c],[x+a,y+b,z+c],[x,y+b,z+c]]};
function projected(v){let x=v[0]-1882.5,y=v[1],z=v[2]-600;let xx=Math.cos(yaw)*x-Math.sin(yaw)*y,yy=Math.sin(yaw)*x+Math.cos(yaw)*y;let zz=z*Math.cos(pitch)-yy*Math.sin(pitch);let depth=yy*Math.cos(pitch)+z*Math.sin(pitch);let scale=canvas.clientWidth/5000*zoom;return [canvas.clientWidth/2+xx*scale,canvas.clientHeight/2-zz*scale,depth]}
const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];
function wire(p,color){const q=verts(p).map(projected);ctx.strokeStyle=color;ctx.lineWidth=1;for(let [a,b] of edges){ctx.beginPath();ctx.moveTo(q[a][0],q[a][1]);ctx.lineTo(q[b][0],q[b][1]);ctx.stroke()}}
function draw(){let dpr=devicePixelRatio||1;canvas.width=canvas.clientWidth*dpr;canvas.height=canvas.clientHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);wire({xyz:[0,-745,240],size:[3765,1490,500]},'#536a85');wire(layout.excluded_solid,'#f43f5e');wire({xyz:[1100,-620,740],size:[1370,1240,660]},'#536a85');for(let x of [800,2960])for(let y of [-615,615]){const q=[];for(let i=0;i<=40;i++)q.push(projected([x+280*Math.cos(i*Math.PI/20),y,280+280*Math.sin(i*Math.PI/20)]));ctx.strokeStyle='#6a809b';ctx.beginPath();q.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.stroke()}
let faces=[];for(let p of layout.parts){let vv=verts(p).map(projected);for(let f of [[0,1,2,3],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]])faces.push({p,points:f.map(i=>vv[i]),z:f.reduce((t,i)=>t+vv[i][2],0)/4})}faces.sort((a,b)=>a.z-b.z);for(let f of faces){ctx.fillStyle=f.p.color+'95';ctx.strokeStyle=f.p.color;ctx.lineWidth=1.2;ctx.beginPath();f.points.forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fill();ctx.stroke()}
for(let p of layout.parts){let q=projected(p.xyz.map((x,i)=>x+p.size[i]/2));ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.fillText(p.id,q[0],q[1])}
for(let ln of layout.lines){ctx.strokeStyle=ln.color;ctx.lineWidth=2;ctx.beginPath();ln.points.map(projected).forEach((v,i)=>i?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.stroke()}}
function overlap(a,b,pad=0){return a.xyz.every((x,i)=>x-pad<b.xyz[i]+b.size[i]&&b.xyz[i]-pad<x+a.size[i])}
function check(){let hard=[],soft=[];for(let [i,a] of layout.parts.entries()){if(overlap(a,layout.excluded_solid))hard.push(a.id+' ↔ салон');for(let b of layout.parts.slice(i+1)){if(overlap(a,b))hard.push(a.id+' ↔ '+b.id);else if(overlap(a,b,100))soft.push(a.id+' ↔ '+b.id)}}el('collisions').innerHTML='<p class="'+(hard.length?'warn':'')+'">'+(hard.length?'Пересечения: '+hard.join(', '):'Пересечений целевых тел нет')+'</p><p class="small">Зазоры менее 100 мм: '+(soft.join(', ')||'не найдены')+'</p>'}
function populate(){el('part').innerHTML=layout.parts.map(p=>'<option value="'+p.id+'">'+p.id+' • '+p.name+'</option>').join('');el('legend').innerHTML=layout.parts.map(p=>'<span><i class="dot" style="background:'+p.color+'"></i>'+p.id+' '+p.name+'</span>').join('');el('layoutStatus').textContent=layout.status;selectPart();draw();check()}
function selectPart(){let p=layout.parts.find(p=>p.id===el('part').value);el('coords').innerHTML='<label>Начальная координата XYZ, мм</label><div class="row">'+p.xyz.map((v,i)=>'<label>'+['X','Y','Z'][i]+' <input class="coord" type="number" step="10" data-i="'+i+'" value="'+v+'"></label>').join('')+'</div>';el('partInfo').textContent=p.size.join(' × ')+' мм. '+p.role;for(let input of el('coords').querySelectorAll('input'))input.addEventListener('input',()=>{if(Number.isFinite(input.valueAsNumber)){p.xyz[Number(input.dataset.i)]=input.valueAsNumber;draw();check()}})}
el('layoutChoice').onchange=()=>{layout=structuredClone(ORIGINAL[Number(el('layoutChoice').value)]);populate()};el('part').onchange=selectPart;el('reset').onclick=()=>{layout=structuredClone(ORIGINAL[Number(el('layoutChoice').value)]);populate()};el('top').onclick=()=>{yaw=0;pitch=Math.PI/2;draw()};el('side').onclick=()=>{yaw=0;pitch=0;draw()};el('iso').onclick=()=>{yaw=-.55;pitch=.65;draw()};el('export').onclick=()=>{let blob=new Blob([JSON.stringify(layout,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='layout.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.008;pitch=Math.max(-1.5,Math.min(1.5,pitch+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];draw()};canvas.onpointerup=()=>drag=null;canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.4,Math.min(2.5,zoom*Math.exp(-e.deltaY*.001)));draw()},{passive:false});window.addEventListener('resize',draw);
const fmt=(x,n=1)=>Number(x).toLocaleString('ru-RU',{maximumFractionDigits:n,minimumFractionDigits:n});
function update(){const s=DATA.scenarios[Number(el('scenario').value)],v=Number(el('speed').value)/3.6,m=el('mass').valueAsNumber,g=Number(el('grade').value)/100,cfg=DATA.inputs.vehicle;if(!(m>0&&Number.isFinite(m))){el('powerStatus').textContent='Введите положительную массу.';return}el('speedLabel').textContent=fmt(v*3.6,0);el('gradeLabel').textContent=fmt(g*100);let theta=Math.atan(g);const force=m*9.80665*(cfg.rolling_coefficient*Math.cos(theta)+Math.sin(theta))+.5*cfg.air_density_kg_m3*cfg.CdA_m2*v*v;const kw=force*v/1000/cfg.transmission_efficiency,scale=(kw+s.case.aux_shaft_kW)/(s.case.net_drive_kW+s.case.aux_shaft_kW),r=s.rated;el('metrics').innerHTML=[['Нужно к КПП',kw,'кВт'],['Горелка',r.burner_LHV_kW*scale,'кВт НТС'],['Пар',r.steam_kg_h*scale,'кг/ч'],['Отвод тепла',r.condenser_kW*scale,'кВт'],['Топливо',r.diesel_L_h*scale,'л/ч'],['Подпитка',r.makeup_kg_h*scale,'кг/ч']].map(([label,value,unit])=>'<div class="metric"><span>'+label+'</span><strong>'+fmt(value)+'</strong><small>'+unit+'</small></div>').join('');const beyond=kw>s.case.net_drive_kW;el('powerStatus').textContent=beyond?'Режим превышает номинальную полезную мощность. Расход показан как математическая экстраполяция; режим недостижим при выбранном номинале.':'Мощности в установившейся модели достаточно. Разгон, охлаждение и дорожный допуск требуют отдельных проверок.';let range=v*3.6*Math.min(s.case.fuel_L/(r.diesel_L_h*scale),s.case.water_L*.8/(r.makeup_kg_h*scale));el('rangeInfo').textContent='Расчет до топлива или воды: '+fmt(range,0)+' км. Без прогрева, остановок и резерва топлива.';el('budget').textContent='Целевой бюджет НИОКР: '+s.case.budget_RUB.map(x=>fmt(x/1e6)).join('–')+' млн ₽ или '+s.case.budget_EUR.map(x=>fmt(x/1000,0)).join('–')+' тыс. €. Это независимые диапазоны планирования, не рыночная смета.'}
for(let id of ['scenario','speed','grade','mass'])el(id).addEventListener('input',()=>{if(id==='scenario'){const s=DATA.scenarios[Number(el('scenario').value)];el('speed').value=s.case.target_kmh;el('mass').value=s.mass.running_mass_kg}update()});
const rows=[['Мощность к КПП, кВт',s=>fmt(s.case.net_drive_kW)],['Мощность машины на валу, кВт',s=>fmt(s.rated.gross_engine_kW)],['Пар, кг/ч',s=>fmt(s.rated.steam_kg_h)],['Горелка, кВт НТС',s=>fmt(s.rated.burner_LHV_kW)],['Конденсатор, кВт',s=>fmt(s.rated.condenser_kW)],['Топливо, л/ч',s=>fmt(s.rated.diesel_L_h)],['Масса с водителем, кг',s=>fmt(s.mass.running_mass_kg)],['Остаток до 1200 кг, кг',s=>fmt(s.mass.remaining_total_payload_kg)]];el('summary').innerHTML='<tr><th>Полная нагрузка</th>'+DATA.scenarios.map(s=>'<th>'+s.case.id+'</th>').join('')+'</tr>'+rows.map(([label,fn])=>'<tr><td>'+label+'</td>'+DATA.scenarios.map(s=>'<td>'+fn(s)+'</td>').join('')+'</tr>').join('');populate();update();
</script></body></html>'''
(ROOT/'index.html').write_text(template.replace('__DATA__',json.dumps(data,ensure_ascii=False)).replace('__LAYOUTS__',json.dumps(layouts,ensure_ascii=False)))
