import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {tubeVolumeCm3} from './web/engine-distribution-model.js';
const meta=JSON.parse(fs.readFileSync('models/fitted-radial-engine.json'));
const connections=meta.routes.map(r=>({name:r.name,length_mm:r.length_mm,inside_mm:r.spec.inside_mm,volume_cm3:tubeVolumeCm3(r.length_mm,r.spec.inside_mm),purpose:r.name.startsWith('Камера ')?'One bidirectional passage between its cylinder chamber and the distributor.':r.name.startsWith('Подача ')?'Fresh-steam plenum to P.':r.name.startsWith('Выпуск ')?'T to exhaust plenum.':r.name.includes('выпуск')?'Exhaust plenum to condenser circuit.':'Steam generator to fresh-steam plenum.'}));
const perCylinder=Array.from({length:7},(_,i)=>({cylinder:i+1,chambers:Object.fromEntries(['A','B'].map(ch=>{
 const r=connections.find(r=>r.name===`Камера ${i+1}${ch}`),area=Math.PI*(40**2-(ch==='B'?9.6**2:0))/4,swept=area*45/1000,geometricClearance=area*.75/1000;
 return [ch,{tube_length_mm:r.length_mm,tube_volume_cm3:r.volume_cm3,cylinder_clearance_cm3:geometricClearance,swept_cm3:swept,connected_clearance_lower_bound_cm3:geometricClearance+r.volume_cm3,clearance_over_swept_lower_bound:(geometricClearance+r.volume_cm3)/swept,excluded:'Distributor galleries, valve pockets, fittings. No residual-mass or condensation solution.'}];
 }))}));
const audit={date:'2026-10-10',scope:'Default seven D40/S45 double-acting engine',status:'Functional distribution corrected; real hardware operation NOT validated',findings:[
 'The previous four-hole hollow valve box did not model partitions, valve seats or closures; its literal pressure-volume interpretation joined P,A,B,T.',
 'Two chamber pipes per cylinder are sufficient when a real distributor alternates admission and exhaust through each pipe. A/B are bidirectional, P/T are separate supply/exhaust.',
 'The new 3D insert is an explicitly symbolic four-valve functional diagram, not a dimensioned pressure manifold. Channel radii and illustrated gate movements do not specify manufacturing dimensions.',
 'B pipes now take a shorter route around the plenums and below the crosshead plane. No pipe has been removed without preserving its function.',
 'External A/B pipe volumes were absent from displayed chamber volumes. They are now included as connected-volume lower bounds.',
 'The unchanged global simulation and sizing estimates still omit actual valve-flow dynamics, residual filling/compression and this clearance contribution. Their power/rpm are unvalidated scenarios.'
 ],ports:{P:'Fresh steam from generator',T:'Spent steam to condenser, then liquid water returns via pumps',A:'Outer/non-rod chamber: admission PA, exhaust AT',B:'Rod-side chamber: admission PB, exhaust BT'},valves_per_cylinder:4,total_commanded_valves:28,phases:[{stage:'A admission',open:['PA','BT']},{stage:'A expansion',open:['BT']},{stage:'A early release',open:['AT','BT']},{stage:'B admission',open:['PB','AT']},{stage:'B expansion',open:['AT']},{stage:'B early release',open:['AT','BT']}],rules:['No chamber inlet and exhaust may overlap in this commanded model.','P must never be connected to T via an open chamber.','Timing follows actual articulated-linkage movement, with assumed 30% stroke cutoff and release after 98.5% expansion stroke.','No cam, valve actuator, lead/lap, compression event, leakage or timing tolerance has yet been designed.'],formulas:{pipe:'V_tube [cm³] = π ID[mm]² L[mm] / 4000',clearance:'V_clearance_connected ≥ V_cylinder_at_dead_centre + V_chamber_pipe',displacement:'V_swept = area × stroke; adding pipe volume does not increase displacement'},connections,per_cylinder:perCylinder,remaining_engine_work:['Dimension and select the distributor architecture; a slide valve is an alternative, not a component already designed.','Design common-shaft-synchronised actuation and stop/failure states.','Solve transient chamber mass, energy and actual steam properties, with external/internal dead volumes and valve discharge coefficients.','Provide specified chamber drains, rod glands, oil separation/lubrication, thermal clearances and rated joints.','Rebuild and verify the stronger mechanical CAD; validate pressure strength, fatigue and hot/cold properties.'],sources:[{title:'Science Museum: one slide valve replaced four valves in early double-acting engines',url:'https://collection.sciencemuseumgroup.org.uk/objects/co51227/representative-sectional-model-of-common-or-locomotive-simple-slide-valve-arranged-with-7-others'}],input_sha256:Object.fromEntries(['models/fitted-radial-engine.json','web/shared-radial-geometry.js','web/shared-radial-model.js','web/engine-distribution-model.js','web/engine-distributor-geometry.js'].map(p=>[p,createHash('sha256').update(fs.readFileSync(p)).digest('hex')]))};
fs.writeFileSync('engine-distribution-audit.json',JSON.stringify(audit,null,2)+'\n');
console.log(JSON.stringify({A:perCylinder[0].chambers.A,B:perCylinder[0].chambers.B,size_mm:meta.bounds.size_mm}));
