import fs from 'node:fs';
import crypto from 'node:crypto';
import {strengthStudy,strengthDefaults} from './web/engine-strength-model.js';
import {sizeEngine} from './web/engine-sizing-model.js';
const data=JSON.parse(fs.readFileSync('engine-sizing.json')).input,fit=JSON.parse(fs.readFileSync('engine-bore-fit.json'));
const rows=fit.rows.map(f=>{
 const candidate={id:'independent-bore-'+f.bore_mm,count:7,bore:f.bore_mm,stroke:45,rod:9.6,output_ratio:1,size_mm:f.size_mm};
 const thermal=sizeEngine(data,candidate,{heat_kW:50});
 return {geometry:f,thermal,working_strength:strengthStudy(f.bore_mm,thermal.crank_rpm),overspeed_strength:strengthStudy(f.bore_mm,strengthDefaults.overspeed_rpm)};
});
const inputs=['web/engine-strength-model.js','web/shared-radial-model.js','web/shared-radial-geometry.js','web/engine-sizing-model.js','engine-sizing.json','engine-bore-fit.json','layout-fitted.json'];
const result={date:'2026-10-10',status:'Предварительная оценка цилиндров с неизменным ходом45 мм; прежний механизм не проходит принятый прочностной экран. Усиление не внедрено и не аттестовано.',assumptions:strengthDefaults,
 sources:[{title:'Ovako · 42CrMo4 +QT, свойства зависят от состояния и сечения',url:'https://steelnavigator.ovako.com/steel-grades/42crmo4/',use:'550 MPa room-temperature conservative illustrative yield across +QT sections up to160mm, not hot/welded material property'},{title:'IIT / NPTEL · изгиб, кручение и комбинированное напряжение',url:'https://archive.nptel.ac.in/content/storage2/courses/105105104/pdf/m6l16.pdf',use:'mechanics of elastic stress screening'},{title:'GGB · DU, допустимая скорость и pV для сухого и масляного режимов',url:'https://www.ggbearings.com/fr/nos-produits/paliers-metal-polymeres/du',use:'dry PV1.8 and oil sliding speed5 m/s are distinct; dry PV is not an oil rating'},{title:'NSK · статистический ресурс подшипников качения',url:'https://www.nsk.com/am-en/tools-resources/knowledge-center/bearing-abcs/dynamic-load-ratings-and-fatigue-life/',use:'L10 is statistical rolling fatigue, not a life formula for our sliding bushings'}],
 limitations:['Клапанные соединения исправлены на функциональном уровне. Прежние оценки оборотов и мощности не учитывают мёртвый объём трубок A/B, внутренние полости клапанов и реальную карту расходов. Они не подтверждены этим расчётом.', 'Кузов — игровая сетка yatloo, подвеска статическая; обмеры, ход подвески и горячие зазоры неизвестны.','Прочностной экран110 МПа — явно принятая гипотеза550/5 при комнатной температуре. Это не допустимое напряжение для металла при250 °C.','15 бар абсолютного — отдельный сценарий нагрузки, не разрешённое давление и не настройка защиты.2600 об/мин — исследовательский сценарий, не допустимая частота вращения.','Масса крейцкопфа и доли шатуна задана гипотезой0,35 кг; инерция вращающейся вилки и собственная распределённая инерция шатунов, дисбаланс, трение, удары и гидроудар не решены.','Передача усилия решена по кинематике нынешних шарниров24 мм и равновесию главного шатуна. Предлагаемая более крупная головка требует нового радиуса шарниров и пересчёта кинематики.','Размеры усиления — начальный прочностной подбор отдельных сечений. Новая двухщёчная конструкция, вилки, отверстия и подшипники требуют нового CAD и повторного аудита; в 3D показаны только увеличенные цилиндры на старом механизме.','Ламе относится к гладкой стенке без портов. Оценка крышки — полосовая модель сплошной пластины; порты, болты, сальник, предварительная затяжка и термические напряжения не рассчитаны.','Усталость и ресурс за730 дней не подтверждены: отсутствуют S–N при температуре, обработка, коэффициенты надрезов, история нагрузок, сертифицированный материал, смазка и испытания.','Три прежних конфликта труб общей сборки и ранее найденные проходы через панели кузова этим исследованием не устранены.'],
 mass_model:'7850 kg/m3 × (πD²/4 ×7.5mm + πd²/4 ×67.5mm) + .35kg per cylinder',
 pressure_model:'Gas force from absolute chamber pressures relative to 1bar crankcase; admission/expansion/exhaust states follow actual articulated kinematics; expansion pV^1.15. This load diagram is illustrative and is NOT a calibrated power prediction.',
 bound_model:'180 angle samples ×128 independent chamber-force endpoint combinations, with calculated reciprocating inertia; all extrema ×1.5. Includes arbitrary valve load combinations, not simultaneous sum of seven axial forces.',
 proposed_topology:{main_journal_mm:45,piston_rod_mm:14,crank_web_width_mm:80,crank_web_thickness_mm:25,crankpin_mm:40,double_cheek_required:true,crankpin_bearing_length_mm:24,crosshead_pin_mm:16,slave_pin_mm:16,rod_net_width_mm:36,rod_thickness_mm:12,cylinder_wall_mm:5,head_first_guess_mm:8,master_fork_cheek_mm:12,master_fork_outer_diameter_mm:120,new_articulation_radius_mm:40,new_articulation_radius_required:true,not_in_3d:true},
 input_sha256:Object.fromEntries(inputs.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')])),rows};
fs.writeFileSync('engine-strength-study.json',JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(rows.map(r=>({D:r.geometry.bore_mm,V:r.thermal.geometry.swept_L,n:r.thermal.crank_rpm,F:r.working_strength.working_force_A_N,currentShaft:r.overspeed_strength.current.shaft_vm_MPa,proposedShaft:r.overspeed_strength.proposed.shaft_vm_MPa,proposedPin:r.overspeed_strength.proposed.crankpin_vm_MPa,joint:r.overspeed_strength.proposed_small_joint,bound:r.overspeed_strength.design_loads})),null,2));
