import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {sizeEngine,heatForPower} from './web/engine-sizing-model.js';
const data=JSON.parse(fs.readFileSync('engine-sizing.json')),checks=[];
const test=(name,pass)=>{assert.ok(pass,name);checks.push({name,pass:true});},near=(a,b,e=1e-8)=>Math.abs(a-b)<e;
const c=data.candidates[2],v=sizeEngine(data.input,c),two=sizeEngine(data.input,data.candidates[0]),large=sizeEngine(data.input,data.candidates[1]);
test('Seven D32/S36 cylinders have 0.202670425 litres of displacement',near(v.geometry.swept_L,7*Math.PI*.032**2/4*.036*1000));
test('Rod-side displacement uses D32 and d7.68, not the old rod',near(v.geometry.double_L,7*Math.PI*(2*.032**2-.00768**2)/4*.036*1000));
test('Changing cylinder volume alone does not change heater-limited shaft power',near(two.shaft_kW,v.shaft_kW)&&near(large.shaft_kW,v.shaft_kW));
test('Smaller cylinder capacity requires proportionately faster cycling',near(v.crank_rpm/large.crank_rpm,large.geometry.double_L/v.geometry.double_L));
test('Power uses the isentropic enthalpy drop, not boiler heat or swept litres',near(v.shaft_kW,(v.mass_kg_h/3600)*400354.2579572415*.5*.9/1000));
test('Metric horsepower conversion is explicit',near(v.shaft_hp,v.shaft_kW*1000/735.49875));
test('Combined water, boiler and pump energy balance closes',Math.abs(v.energy_residual_W)<1e-8);
test('Closed-cycle cooling includes receiver subcooling',v.subcool_kW>3.49&&near(v.reject_kW,v.main_reject_kW+v.subcool_kW));
test('Air heat balance and continuity independently reproduce flow and speed',near(v.air_m3_s,v.reject_kW*1000/(1.18*1005*25))&&near(v.air_m_s,v.air_m3_s/.05525));
test('Generator losses are charged against the shaft',near(v.aux_shaft_kW,v.electric_kW/.85)&&near(v.net_kW,v.shaft_kW-v.aux_shaft_kW));
test('Seven local crank cycles run twice as fast as common output shaft',near(v.crank_rpm,2*v.output_rpm));
test('Mean piston speed uses stroke in metres and crank RPM',near(v.mean_piston_m_s,2*.036*v.crank_rpm/60));
test('Output shaft torque reproduces shaft power independently of volume',near(v.torque_output_Nm*v.output_rpm*2*Math.PI/60,v.shaft_kW*1000));
test('Built compact assembly and analytic core bounds remain inside the reserve',c.core_radius_bound_mm*2<460&&c.core_height_bound_mm<420&&v.fits_reserve_box&&v.has_current_mesh_bounds&&c.size_mm[0]>c.budget_mm[0]);
test('Current small GLB assemblies are distinguished from the oversized star',two.has_current_mesh_bounds&&two.fits_reserve_box&&!large.fits_reserve_box);
test('Compact star remains just below provisional 2600 RPM at 50 kW',v.crank_rpm>2580&&v.crank_rpm<2600&&v.engine_speed_study_ok);
test('The existing 0.85 filling assumption increases required cycle frequency',near(v.crank_rpm/sizeEngine(data.input,c,{filling_factor:1}).crank_rpm,1/.85));
const eighty=sizeEngine(data.input,c,{heat_kW:80});
test('A larger heater request exposes excessive compact-engine RPM',!eighty.engine_speed_study_ok&&eighty.crank_rpm>3900);
test('Auxiliary-energy deficit remains visible, rather than being clamped away',eighty.net_kW<0);
const hotter=sizeEngine(data.input,c,{air_rise_K:45});
test('Allowing hotter exhaust air changes cooling flow, not steam-engine shaft output',near(hotter.shaft_kW,v.shaft_kW)&&hotter.fan_kW<v.fan_kW&&hotter.net_kW>v.net_kW);
const better=sizeEngine(data.input,c,{eta_is:.6});
test('Increasing expansion efficiency increases work and lowers rejected heat',near(better.shaft_kW/v.shaft_kW,1.2)&&better.reject_kW<v.reject_kW);
test('Shaft efficiency stays below the same-state ideal Rankine bound',v.effective_thermal_efficiency<v.ideal_rankine_efficiency);
const target=sizeEngine(data.input,data.candidates[0],{heat_kW:heatForPower(data.input,40)});
test('Inverse thermal sizing reproduces 40 metric horsepower',near(target.shaft_hp,40));
test('Forty horsepower exceeds the current source capacity',target.heat_kW>439&&target.fuel_input_kW>516&&!target.source_power_ok);
test('High air speed does not produce a false fan or useful-power prediction',!target.air_budget_applicable&&target.fan_kW===null&&target.net_kW===null);
let rejected=0;for(const o of [{heat_kW:NaN},{eta_is:1.1},{air_rise_K:0},{eta_electric:0},{cutoff:0},{air_area_m2:-1}])try{sizeEngine(data.input,c,o);}catch{rejected++;}
test('Invalid parameters cannot enter the calculation',rejected===6);
const sources=['web/engine-sizing-model.js','web/engine-sizing.js','web/engine-sizing.html','engine-sizing.json','build_engine_sizing.mjs','engine_sizing_page.py','build_site.py','workspace_ui.py','build_knowledge.py','verify_engine_sizing.mjs'];
fs.writeFileSync('engine-sizing-checks.json',JSON.stringify({status:'passed',scope:'Preliminary dimensions and approximate mass/energy/power/cooling budgets; CAD fitting is checked separately; no component rating or manufacture validation',checks,source_sha256:Object.fromEntries(sources.map(p=>[p,createHash('sha256').update(fs.readFileSync(p)).digest('hex')]))},null,2)+'\n');
console.log(JSON.stringify({status:'passed',checks:checks.length,volume_L:v.geometry.swept_L,shaft_kW:v.shaft_kW,net_kW:v.net_kW,target40_heat_kW:target.heat_kW}));
