import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {pistonForces,pistonKinematics,forceDefaults} from './web/piston-force-model.js';
import {cylinderCycle,engineGeometry as K} from './web/double-acting-cycle.js';
const checks=[];
const test=(name,pass)=>{assert.ok(pass,name);checks.push({name,pass:true});};
const near=(a,b,tolerance=1e-8)=>Math.abs(a-b)<tolerance;
const at=deg=>pistonForces(deg*Math.PI/180);
test('Admission pressure acts downward on the top face',near(at(20).forces.faceA_N,-9e5*Math.PI*.1**2/4)&&near(at(20).forces.faceB_N,0));
test('Rod-side admission acts upward on the reduced annular area',near(at(200).forces.faceB_N,9e5*Math.PI*(.1**2-.024**2)/4)&&near(at(200).forces.faceA_N,0));
test('All areas convert millimetres to metres before pressure multiplication',near(at(20).areas.A_m2,.007853981633974483)&&near(at(20).areas.B_m2,.007401592291857553));
const vacuum=pistonForces(.5,{inlet_bar:.5});test('Subambient gauge loading reverses the equivalent arrow',vacuum.forces.faceA_N>0);
const common=pistonForces(.5,{inlet_bar:2,exhaust_bar:2,equalized:true});
test('Equal absolute pressures account for ambient force on exposed rod end',near(common.forces.gas_N,-1e5*common.areas.rod_m2));
let maxFirstError=0,maxSecondError=0,maxBalance=0,finite=true,alignment=true;
const h=.0001,z=a=>cylinderCycle(a).pistonZ_mm/1000;
for(let d=0;d<360;d+=.5){const a=d*Math.PI/180,v=pistonForces(a),m=v.motion;
 maxFirstError=Math.max(maxFirstError,Math.abs(m.dz_m_rad-(z(a+h)-z(a-h))/(2*h)));
 maxSecondError=Math.max(maxSecondError,Math.abs(m.ddz_m_rad2-(z(a+h)-2*z(a)+z(a-h))/(h*h)));
 maxBalance=Math.max(maxBalance,Math.abs(v.residual_Z_N),Math.abs(v.residual_Y_N));
 finite&&=Object.values(v.forces).every(Number.isFinite)&&Object.values(m).every(Number.isFinite)&&v.pressures.A.pressure_Pa>0&&v.pressures.B.pressure_Pa>0;
 alignment&&=near(v.forces.rod_Y_N*m.q_m+v.forces.rod_Z_N*m.r_m*Math.sin(a),0,1e-7);
}
test('Exact velocity agrees with independently differentiated piston position',maxFirstError<1e-8);
test('Exact acceleration agrees with independent second difference',maxSecondError<1e-7);
test('Newton force balance closes in Z and transverse Y through a full turn',maxBalance<1e-8);
test('Rod reaction remains collinear with the actual rod',alignment);
test('All phases yield finite forces and positive absolute pressures',finite);
const omega=forceDefaults.rpm*2*Math.PI/60,r=K.crankRadius/1000,l=K.connectingRod/1000;
test('Top dead centre acceleration equals −rω²(1+r/L)',near(at(0).motion.acceleration_m_s2,-r*omega**2*(1+r/l)));
test('Bottom dead centre acceleration equals rω²(1−r/L)',near(at(180).motion.acceleration_m_s2,r*omega**2*(1-r/l)));
test('Inertia scales with physical RPM squared',near(pistonForces(.7,{rpm:600}).forces.ma_N,4*pistonForces(.7,{rpm:300}).forces.ma_N));
test('Mass changes inertia linearly',near(pistonForces(.7,{mass_kg:6}).forces.ma_N,2*pistonForces(.7,{mass_kg:3}).forces.ma_N));
test('Zero RPM removes inertia and moving friction',near(pistonForces(.7,{rpm:0}).forces.ma_N,0)&&near(pistonForces(.7,{rpm:0}).forces.friction_N,0));
test('Friction opposes velocity in both strokes',at(20).forces.friction_N>0&&at(200).forces.friction_N<0);
const e=at(100).pressures.A;
test('Closed expansion obeys chosen pV^k law',e.law==='expansion'&&near(e.pressure_Pa*e.volume_m3**1.2,e.reference_Pa*e.reference_m3**1.2)&&e.pressure_Pa<1e6);
const c=at(175).pressures.B;
test('Trapped compression rises from exhaust pressure without an arbitrary cap',c.law==='compression'&&c.pressure_Pa>1e5&&near(c.pressure_Pa*c.volume_m3**1.2,c.reference_Pa*c.reference_m3**1.2));
let lo=0,hi=Math.PI;for(let i=0;i<60;i++){const mid=(lo+hi)/2;if(cylinderCycle(mid).progress<.3)lo=mid;else hi=mid;}
test('Pressure is continuous at the admission cutoff volume',Math.abs(pistonForces(lo-1e-9).pressures.A.pressure_Pa-pistonForces(hi+1e-9).pressures.A.pressure_Pa)<.1);
test('Moving force calculation is periodic across signed full turns',near(pistonForces(-.4).forces.gas_N,pistonForces(2*Math.PI-.4).forces.gas_N));
const accelerated=pistonKinematics(.7,300,2),constant=pistonKinematics(.7,300,0);
test('General kinematics also accounts for angular acceleration',near(accelerated.acceleration_m_s2,constant.acceleration_m_s2+2*constant.dz_m_rad));
const inertiaOnly=pistonForces(.7,{mass_kg:30,inlet_bar:1,exhaust_bar:1,equalized:true,rpm:2600});
test('Dominant inertia can reverse the rod reaction',Math.sign(inertiaOnly.forces.rod_Z_N)===Math.sign(inertiaOnly.forces.ma_N-inertiaOnly.forces.gravity_N-inertiaOnly.forces.friction_N));
let rejected=0;for(const options of [{rpm:NaN},{mass_kg:0},{exhaust_bar:-1}])try{pistonForces(0,options);}catch{rejected++;}
test('Invalid nonfinite and nonphysical inputs are rejected',rejected===3);
const sources=['web/piston-force-model.js','web/piston-force-view.js','web/piston-force-ui.js','web/double-acting-cycle.js','web/double-acting-view.js','web/assembly-systems.js','web/assembly.js','web/assembly.html','web/double-acting.css','build_site.py','verify_piston_forces.mjs'];
const result={status:'passed',scope:'Approximate per-cylinder pressure cycle and lumped piston/rod/crosshead forces; not a measured indicator diagram, strength calculation or feedback into engine power',defaults:forceDefaults,checks,numerical:{sampled_angles:720,max_first_derivative_error:maxFirstError,max_second_derivative_error:maxSecondError,max_force_balance_residual_N:maxBalance},source_sha256:Object.fromEntries(sources.map(p=>[p,createHash('sha256').update(fs.readFileSync(p)).digest('hex')]))};
fs.writeFileSync('piston-force-checks.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'passed',checks:checks.length,...result.numerical}));
