import fs from 'node:fs';import assert from 'node:assert/strict';import {sizeEngine} from './web/engine-sizing-model.js';import {SteamSimulation} from './web/steam-simulation.js';
const study=JSON.parse(fs.readFileSync('fitted-engine-study.json')),data=JSON.parse(fs.readFileSync('simulation-data.json')),checks=[];const test=(name,ok)=>{assert.ok(ok,name);checks.push({name,passed:true});};const near=(a,b,t=1e-9)=>Math.abs(a-b)<t;
const k=study.selected,v=study.cases[0],opts={cylinders:7,acting_sides:2,engine_bore_m:.04,engine_stroke_m:.045,engine_rod_m:.0096,engine_output_ratio:2};
test('Actual seven bores and strokes give 0.395840674 L',near(v.geometry.swept_L,7*Math.PI*.04**2/4*.045*1000));test('Rod area is subtracted only from the rod-side sweep',near(v.geometry.double_L,7*Math.PI*(2*.04**2-.0096**2)/4*.045*1000));test('Common shaft runs at half crank RPM',near(v.crank_rpm,2*v.output_rpm));test('Torque and shaft speed independently recover power',near(v.torque_output_Nm*v.output_rpm*2*Math.PI/60,v.shaft_kW*1000,1e-8));
const small=sizeEngine(study.input,{...k,bore:32,stroke:36,rod:7.68});test('Increasing volume does not invent extra source-limited power',near(small.shaft_kW,v.shaft_kW)&&small.crank_rpm>v.crank_rpm);test('102 kW thermal is limited by 120 kW source at 85 percent',near(study.cases[1].fuel_input_kW,120));test('Cooling deficit and overspeed are retained',study.cases[1].net_kW<0&&!study.cases[1].engine_speed_study_ok);test('40 HP cannot be claimed for the existing source',study.target_40_hp.heat_kW>439&&!study.target_40_hp.feasible_with_current_source);test('40mm clears the coarse diesel screen and 41mm fails',study.tables[0].conflicts.length===0&&study.tables[1].conflicts.some(x=>x.id==='PIPE_FLUE'));test('Open valve duty uses crank angle rather than treating stroke cutoff as time',study.pipe_screen.mean_inlet_open_fraction>.35&&study.pipe_screen.mean_inlet_open_fraction<.4);
for(const source of data.heat_sources){const sim=new SteamSimulation(data,{...opts,source_id:source.id});sim.start();sim.auto=true;let mass=0,energy=0;for(let i=0;i<1200;i++){const s=sim.step(.05);mass=Math.max(mass,Math.abs(s.mass_residual_kg));energy=Math.max(energy,Math.abs(s.energy_residual_J));}test(source.id+' seven-cylinder mass and energy balances',mass<1e-8&&energy<.02);}
// A full common-shaft turn needs two crank turns. Modulo 2pi would jump halfway.
const turn=new SteamSimulation(data,opts);turn.run=true;turn.phase=0;turn.crankAngle=3*Math.PI;turn.omega=30;turn.step(.05);test('Seven-cylinder common-shaft angle survives second crank revolution',turn.snapshot().crank_angle_rad>2*Math.PI);
const fit=JSON.parse(fs.readFileSync('fitted-engine-fit.json'));test('Core clears body and registered static suspension',fit.enginePart.body_intersections.length===0&&fit.enginePart.stock_intersections.length===0&&fit.enginePart.clearance_mm>=10);test('All four floor pads match 36 samples on the source mesh',fit.contacts.length===4&&fit.contacts.every(x=>x.max_error_mm<.01));test('New boundary joints have matching axes, bores and faces',fit.joints.filter(r=>['PIPE_STEAM','PIPE_EXHAUST_R','PIPE_EXHAUST_L','PIPE_EXHAUST_COMMON'].includes(r.id)).every(r=>r.geometry_valid&&r.metrics.every(j=>j.geometry_ok)));test('New exhaust branches clear body, engine and diesel route',fit.audit.parts.filter(p=>p.id.startsWith('PIPE_EXHAUST')).every(p=>p.body_intersections.length===0)&&!fit.audit.summary.unplanned_mesh_intersections.some(pair=>pair.includes('ENG')||pair.some(id=>id.startsWith('PIPE_EXHAUST'))));test('Global maximum and road readiness are not implied',study.family.maximum_global===false&&study.limitations.length>=6);
fs.writeFileSync('fitted-engine-checks.json',JSON.stringify({status:'passed',checks,scope:'Approximate thermodynamic budget, geometry screen and numerical conservation; not material or manufacturing verification'},null,2)+'\n');console.log(JSON.stringify({status:'passed',checks:checks.length}));
