const {chromium}=require('../tower-battle/node_modules/playwright-core'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[],report=path.join(__dirname,'../reports/steam-zaz968m-strength-2026-10-10');page.on('pageerror',e=>errors.push(e.message));
 const test=(name,ok)=>{assert.ok(ok,name);checks.push({name,passed:true});console.log(name);};
 await page.goto('http://127.0.0.1:8768/docs/engine-strength.html');
 test('Initial detail is D60 working speed with formula-first substitutions',await page.locator('.bore-panel:not([hidden])').textContent().then(s=>s.includes('578')&&s.includes('110 МПа')&&s.includes('0,891')));
 await page.locator('#strengthBore').selectOption('100');await page.locator('#strengthCase').selectOption('overspeed');
 test('Bore and speed selectors show exactly one matching calculation',await page.evaluate(()=>{const a=[...document.querySelectorAll('.bore-panel')].filter(x=>!x.hidden);return a.length===1&&a[0].dataset.bore==='100'&&a[0].dataset.case==='overspeed';}));
 test('3D study link follows chosen bore',await page.locator('#boreModelLink').getAttribute('href').then(s=>s.includes('cylinder-bore=100')));
 await page.setViewportSize({width:390,height:844});test('Formula page has no mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:1000});
 await page.locator('#strengthBore').selectOption('60');await page.locator('#strengthCase').selectOption('working');
 // Export a plain document so workspace controls cannot affect print layout.
 const printContent=require('child_process').execFileSync('python3',['-c',"import json;from engine_strength_page import content;print(content(json.load(open('engine-strength-study.json'))))"],{cwd:__dirname}).toString();
 const printPage=await browser.newPage();printPage.on('pageerror',e=>errors.push('PDF: '+e.message));
 await printPage.setContent('<!doctype html><html lang="ru"><meta charset="utf-8"><title>Увеличение цилиндров и прочность · Ø60 ×45</title><style>html,body{background:white;color:black}body{font:12px/1.5 Arial,sans-serif;margin:0}h1{font-size:24px}h2{font-size:18px;break-after:avoid}h3{font-size:14px;break-after:avoid}section{margin-bottom:24px}.thermal-formula{border:1px solid #ccc;padding:12px;margin:12px 0;break-inside:avoid}code{font-family:Arial,sans-serif;font-size:13px;overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;font-size:10px}th,td{padding:7px;border-bottom:1px solid #ccc;text-align:left;vertical-align:top}.strength-controls,.hero-actions{display:none}[hidden]{display:none}a{color:#174d73}ul{padding-left:18px}</style><main>'+printContent+'</main></html>');
 // Candidate D60 in both speed scenarios; all variants are in the interactive report.

 await printPage.evaluate(()=>{document.querySelectorAll('.bore-panel').forEach(p=>p.hidden=p.dataset.bore!=='60');document.querySelectorAll('details').forEach(e=>e.open=true);});
 await printPage.pdf({path:path.join(__dirname,'engine-strength-report.pdf'),format:'A4',printBackground:true,margin:{top:'12mm',bottom:'12mm',left:'12mm',right:'12mm'}});
 await printPage.close();
 test('Standalone PDF exported',fs.statSync(path.join(__dirname,'engine-strength-report.pdf')).size>30000);
 await page.goto('http://127.0.0.1:8768/docs/assembly.html?component=ENG&cylinder-bore=60');await page.waitForFunction(()=>window.steamAssemblyProject?.systems,{timeout:120000});
 const state=await page.evaluate(()=>{const p=window.steamAssemblyProject,e=p.models.get('ENG').radialEngine,s=p.systems.simulationSnapshot();return {config:e.config,cylinder_count:e.cylinders.length,piston_diameter_mm:e.cylinders[0].piston.geometry.parameters.radiusTop*2,simulation:s.engine_geometry,route_count:e.routes.length,study_note:document.getElementById('layoutNotes').textContent};});
 test('D60 study has seven actual enlarged bores and unchanged45mm kinematics',state.config.bore===60&&state.config.kinematicBore===40&&state.config.stroke===45&&state.config.rod===9.6&&state.cylinder_count===7&&Math.abs(state.piston_diameter_mm-59.7)<1e-8);
 test('Simulation uses actual D60 bore and double action',state.simulation.engine_bore_m===.06&&state.simulation.engine_stroke_m===.045&&state.simulation.cylinders===7&&state.simulation.acting_sides===2);
 test('Study warns that the mechanical design was not strengthened',state.study_note.includes('без усиления')&&state.study_note.includes('прочность'));
 const pipes=await page.evaluate(()=>{const e=window.steamAssemblyProject.models.get('ENG').radialEngine;return e.routes.filter(r=>r.role==='outlet').map((r,i)=>{const p=e.portRecords[i].valve_ports.find(p=>p.id==='out'),at=e.cylinders[i].at,first=at(...[p.anchor_mm[0],p.anchor_mm[2],p.anchor_mm[1]]),direction=r.points[1].map((v,k)=>v-r.points[0][k]);let valid=true;const trim=r.points.map((_,j)=>{if(j===0||j===r.points.length-1)return 0;const a=r.points[j].map((v,k)=>v-r.points[j-1][k]),b=r.points[j+1].map((v,k)=>v-r.points[j][k]),L=Math.hypot(...a)*Math.hypot(...b),angle=Math.acos(Math.max(-1,Math.min(1,a.reduce((s,v,k)=>s+v*b[k],0)/L)));return r.bend_radius_mm*Math.tan(angle/2);});for(let j=1;j<r.points.length;j++)if(Math.hypot(...r.points[j].map((v,k)=>v-r.points[j-1][k]))+1e-8<trim[j-1]+trim[j])valid=false;return {name:r.name,endpoint_error_mm:Math.hypot(...first.map((v,k)=>v-r.points[0][k])),side_port:p.outward[0]===-1,bends_fit:valid,direction};});});
 test('Seven rerouted exhaust branches terminate at actual side ports',pipes.length===7&&pipes.every(p=>p.side_port&&p.endpoint_error_mm<1e-8));test('Full radius elbows fit all new exhaust segments without backward spans',pipes.every(p=>p.bends_fit));
 await page.locator('#engineCycleMode').selectOption('manual');await page.locator('#engineCycleAngle').evaluate(e=>{e.value=65;e.dispatchEvent(new Event('input'));});await page.locator('#cadViewport').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(report,'bore60-in-car.png')});
 await page.goto('http://127.0.0.1:8768/docs/assembly.html?component=ENG');await page.waitForFunction(()=>window.steamAssemblyProject?.systems,{timeout:120000});test('Normal project link still defaults to D40 original mechanism',await page.evaluate(()=>window.steamAssemblyProject.models.get('ENG').radialEngine.config.bore===40));
 test('No browser exceptions',errors.length===0);const result={status:'passed',checks,state,pipes,errors};fs.writeFileSync(path.join(__dirname,'engine-strength-browser-checks.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:'passed',checks:checks.length,errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
