import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {compareHeat} from './web/heat-comparison.js';import {SteamSimulation} from './web/steam-simulation.js';import {wheelLoads,massItems} from './web/wheel-loads.js';
const data=JSON.parse(fs.readFileSync('simulation-data.json')),checks=[];const test=(name,value,detail)=>{checks.push({name,pass:!!value,detail});assert.ok(value,name+': '+JSON.stringify(detail));};
const initial=new SteamSimulation(data).snapshot();test('Initial total pressure includes air, 1 bar absolute',Math.abs(initial.boiler.p-1e5)<1,initial.boiler.p);test('Initial equilibrium temperature 20 C',Math.abs(initial.boiler.T-20)<.0001);test('Table 10 bar / 250 C agrees with baseline h and density',(()=>{const s=new SteamSimulation(data).steam(1e6,250,1.2e5);return Math.abs(s.h-2943222.1652)/2943222.1652<.01&&Math.abs(s.rho-4.29665972)/4.29665972<.015;})());
const simulations={};for(const [name,options,fan]of [...data.heat_sources.map(s=>[s.id,{source_id:s.id},1]),['no_fans',{},0],['small_cooling',{condenser_UA_W_K:50,airflow_m3_s:.05},1]]){const sim=new SteamSimulation(data,options);sim.start();sim.auto=true;sim.fan=fan;let maxMass=0,maxEnergy=0,maxSource=0,peakP=0,firstWorking=null,phases=new Set();for(let i=0;i<18000;i++){const s=sim.step(.05);phases.add(s.phase);if(s.phase===9&&firstWorking===null)firstWorking=s.time;maxSource=Math.max(maxSource,Math.abs(s.source_residual_J));maxMass=Math.max(maxMass,Math.abs(s.mass_residual_kg));maxEnergy=Math.max(maxEnergy,Math.abs(s.energy_residual_J));peakP=Math.max(peakP,s.condenser.p);testFinite(s,i);}
 function testFinite(s,i){if(i%1000===0)test(name+' finite nonnegative inventories at '+i,[s.boiler.T,s.condenser.T,s.rpm,s.speed_kmh,s.boiler.p].every(Number.isFinite)&&[sim.b.M,sim.c.M,sim.r.M,sim.water,sim.fuel].every(x=>x>=0));}
 const end=sim.snapshot();test(name+' conserves water including measured model losses',maxMass<1e-8,maxMass);test(name+' control-volume energy balance',maxEnergy<.001,maxEnergy);test(name+' conservative source-energy store',maxSource<.001,maxSource);if(['no_fans','small_cooling'].includes(name))test(name+' calculated cooling limitation stops model',sim.trip.includes('Противодавление'),sim.trip);else{test(name+' passes all stages to working state',phases.has(9),[...phases]);test(name+' condensate returns without inventory flooding',end.recovered_water_kg>1&&sim.c.M<1&&sim.water>30,{return:end.recovered_water_kg,cond:sim.c.M,makeup:sim.water});test(name+' positive heat-input and shaft-work',end.input_energy_J>0&&end.shaft_energy_J>0);}simulations[name]={first_working_time_s:firstWorking,max_source_residual_J:maxSource,trip:sim.trip,phases:[...phases],peak_condenser_bar_abs:peakP/1e5,max_mass_residual_kg:maxMass,max_energy_residual_J:maxEnergy,last:end};}
const manual=new SteamSimulation(data);test('No sequence advance before start',manual.advance()===false);manual.start();test('First check advances to purge',manual.advance()&&manual.phase===2);test('Purge timer blocks immediate advance',manual.advance()===false);for(let i=0;i<101;i++)manual.step(.05);test('Purge completes after model timer',manual.advance()&&manual.phase===3);manual.stop();test('Emergency stop remains latched',manual.advance()===false&&manual.phase===10);manual.reset();test('Reset clears latch and time',!manual.trip&&manual.time===0&&manual.phase===0);
const force=(name,mutate,substring)=>{const sim=new SteamSimulation(data);sim.start();mutate(sim);sim.step(.05);test(name,sim.trip.includes(substring),sim.trip);};force('Boiler pressure research limit',s=>s.b.E=s.equilibrium(s.b.M,s.b.V,s.b.C,s.b.air,200).E,'генератора');force('Real candidate Cat water temperature',s=>s.r.E=s.r.M*s.liquid(86).u+s.r.C*66,'82');force('Condenser backpressure limit',s=>s.c.E=s.equilibrium(s.c.M,s.c.V,s.c.C,s.c.air,150).E,'Противодавление');force('Engine overspeed research limit',s=>s.omega=3000*2*Math.PI/60,'оборотов');force('Receiver dry protection',s=>s.r.M=1,'воды');
const warm=dt=>{const s=new SteamSimulation(data);s.run=true;s.phase=4;for(let i=0;i<Math.round(5/dt);i++)s.step(dt);return s.snapshot();};const a=warm(.05),b=warm(.025);test('Halved step changes warmup temperature under 0.2 C',Math.abs(a.boiler.T-b.boiler.T)<.2,{a:a.boiler.T,b:b.boiler.T});test('Halved step changes warmup pressure under 0.02 bar',Math.abs(a.boiler.p-b.boiler.p)<2000);
const items=massItems(data),normal=wheelLoads(items),brake=wheelLoads(items,{brake:5}),turn=wheelLoads(items,{lateral:5});for(const [name,c]of [['static',normal],['brake',brake],['turn',turn]])test(name+' exact force and moment equilibrium',c.residuals.every(x=>Math.abs(x)<1e-7),c.residuals);
const front=c=>c.wheels.slice(0,2).reduce((s,r)=>s+r.N,0);test('Braking transfer follows m a h / L',Math.abs(front(brake)-front(normal)-normal.mass_kg*5*normal.cg_m[2]/2.16)<1e-7);test('Left turn transfers load to right wheels',turn.wheels[1].N+turn.wheels[3].N>turn.wheels[0].N+turn.wheels[2].N);test('Unmeasured travel is flagged instead of certified',brake.wheels.some(w=>w.travelExceeded));const symmetric=wheelLoads([{kg:840,xyz_m:[.675+.62*2.16,0,.5]}]);test('Reference corner loads and zero incremental deflection',symmetric.wheels.every(w=>Math.abs(w.delta_mm)<1e-7)&&Math.abs(symmetric.wheels[0].kg_equivalent-159.6)<1e-7);const lifted=wheelLoads(items,{lateral:30});test('Wheel lift invalidates linear support solution',lifted.wheels.some(w=>w.lift)&&!lifted.valid);test('Flue mass follows the shown complete route',data.masses.find(m=>m.id==='PIPE_FLUE').kg>0&&!data.masses.find(m=>m.id==='PIPE_FLUE').source.includes('резерв'));
const delayed=new SteamSimulation(data,{source_id:'wood'});delayed.run=true;delayed.phase=4;for(let i=0;i<200;i++)delayed.step(.05);delayed.stop();const fuelBefore=delayed.fuel,Ebefore=delayed.sourceStored_J;delayed.step(.05);test('Wood retains heat after fuel command is stopped',delayed.fuel===fuelBefore&&delayed.sourceStored_J<Ebefore&&delayed.last.burner>0);
test('Wood residual heat flags post-stop pressure excursion',simulations.wood.last.alerts.some(a=>a.includes('генератора')),simulations.wood.last.alerts);
const comparison=compareHeat(data);for(const r of comparison){test(r.source_id+' source efficiency is distinct from total',r.efficiency>r.overall_efficiency&&r.overall_efficiency>0);test(r.source_id+' fuel-energy equation closes',Math.abs(r.fuel_units_h*r.energy_MJ_per_unit/3.6*r.efficiency-r.heat_kW)<1e-9);test(r.source_id+' condenser energy equation closes',r.condenser_kW>r.shaft_kW&&r.condenser_kW<r.heat_kW);}
test('Wetter wood increases consumption',compareHeat(data,{woodMoisture:40})[1].fuel_units_h>comparison[1].fuel_units_h);test('Electric heating has no combustion-gas flow',comparison[4].flue===null);test('Electric 60kW source respects source power limit',!compareHeat(data,{heat_kW:70})[4].source_capacity_ok);
simulations.default=simulations.diesel;test('Top-level and source-node explanations complete',Object.keys(data.nodes).length===32&&Object.values(data.subnodes).filter(n=>n.owner==='SUSP').length===50&&Object.values(data.subnodes).filter(n=>n.owner==='BODY').length===106);
const pump=new SteamSimulation(data);pump.run=true;pump.phase=3;pump.b.M=1.8;pump.step(.05);const pumpState=pump.snapshot();test('Pump follows 15 lpm at 950 rpm candidate bound',pumpState.pumpRPM>=100&&pumpState.pumpRPM<=950.001&&pumpState.feed<=pump.receiver().rho*.015/60+.001);test('Model includes documented pump dry mass',data.masses.find(m=>m.id==='PMP').kg===8.7);
const result={status:'passed',source_sha256:Object.fromEntries(['simulation-data.json','heat-sources.json','web/steam-simulation.js','web/heat-comparison.js','web/wheel-loads.js'].map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')])),checks,comparison,simulations,loads:normal,brake,scope:'Numerical mass/energy/equilibrium, assumed component responses and quasi-static wheel loads; not real equipment or safety verification'};fs.writeFileSync('simulation-checks.json',JSON.stringify(result,null,2)+'\n');fs.writeFileSync('heat-comparison-results.json',JSON.stringify({conditions:data.comparison_cycle,rows:comparison,scope:result.scope},null,2)+'\n');console.log(JSON.stringify({status:result.status,checks:checks.length,mass_kg:normal.mass_kg,wheel_kg:normal.wheels.map(w=>w.kg_equivalent),default_trip:simulations.default.trip}));
