"""Build a linked procurement register; no catalogue item is implicitly approved."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent

def link(title, url, kind, markets, note='', layer=None):
    return dict(title=title, url=url, kind=kind, markets=markets, note=note, **({'layer':layer} if layer else {}))

metal = [link('BE Group · листы, трубы и профили', 'https://www.begroup.fi/tuotteet', 'material', ['FI'], 'Марка и сечение подбираются по расчёту.'), link('Inoxpoint · металлопрокат и фитинги', 'https://www.inoxpoint.ru/', 'material', ['RU'], 'Каталог, не выбранная спецификация.')]
parts = [link('Автоопт · каталог ЗАЗ-968', 'https://www.autoopt.ru/auto/catalog/car/zaz/zaz-968/8', 'catalogue', ['RU'], 'Сверить исполнение 968М и номер с установленной деталью.'), link('Avtoall · кузов и детали ЗАЗ-968М', 'https://www.avtoall.ru/catalog/zaz-6/legkovye_avtomobili-30/zaz_968m-107/kuzov_i_ego_detali-3/', 'catalogue', ['RU'], 'Возможна блокировка VPN; наличие проверяется в магазине.'), link('Заводской каталог деталей ЗАЗ-968М', 'https://www.saporoshez-968.de/968M_ersatzteilkatalog_russisch.pdf', 'documentation', ['ALL'], 'Для сверки номеров, не магазин.')]
electric = [link('TME Finland · корпуса, автоматика, крепёж', 'https://www.tme.eu/fi/katalog/', 'catalogue', ['FI','EU'], 'Изделия выбираются после схемы управления.'), link('ОВЕН · промышленная автоматика и датчики', 'https://files.owen.ru/catalog/', 'catalogue', ['RU'], 'Диапазоны и независимая защита ещё не определены.')]
insulation = [link('Изотех · ArmaGel HT, купить маты', 'https://www.izoteh.pro/vspenennyy-kauchuk/armacell/armagel-ht', 'material', ['RU'], 'Подобрать толщины слоёв и количество.', 'insulation'), link('Armacell · ArmaGel HT и поставщики', 'https://www.armacell.com/en-US/contact-sales-and-support-teams', 'inquiry', ['ALL'], 'Запросить поставщика для Финляндии / ЕС.', 'insulation'), link('ArmaGel HT · технические данные', 'https://www.armacell.com/sites/default/files/2026/01/09/ArmaGel%20HT%20-%20Technical%20Datasheet%20-%20ru-RU.pdf', 'documentation', ['ALL'], 'Используемый в проекте материал.', 'insulation')]
tube = [link('Swagelok · трубки и принадлежности', 'https://products.swagelok.com/en/all-products/tubing-tube-accessories/tubing/c/811?clp=true', 'catalogue', ['ALL'], 'Точные OD/ID проекта могут отсутствовать в каталоге.', 'pipe'), *[dict(x, layer='pipe') for x in metal]]
jacket = [dict(x, title=x['title']+' · защитный лист', layer='jacket', note='В модели кожух 0,6 мм; марка, швы и крепление не выбраны.') for x in metal]
wires = [link('TME Finland · провода и кабели', 'https://www.tme.eu/fi/katalog/johdot-ja-kaapelit_112533/', 'material', ['FI','EU'], 'Сечение, ток, температура и разъёмы по электрической схеме.'), link('OEM Finland · промышленные кабели', 'https://www.oem.fi/tuotteet/kaapeli/kaapelit', 'catalogue', ['FI'], 'Не считать любой кабель термостойким.'), *electric[1:]]

# Descriptions are project requirements, not supplier claims or fabrication instructions.
specs = {
 'ENG': ('custom','Готовая автомобильная паровая машина не выбрана. Модель показывает резерв компоновки.', ['Для B: около 27,6 кВт на валу до вспомогательных нагрузок.', 'Подтвердить обороты, момент, расход пара, массу, смазку, крепления и сервисные зазоры.'], [link('Spilling · запрос паровой машины по ТЗ', 'https://www.spilling.de/', 'inquiry', ['ALL'], 'Промышленный изготовитель; компактный подходящий типоразмер не подтверждён.'), *metal]),
 'STM': ('custom','Заказывать расчёт и изготовление у специалиста по парогенераторам; витки в 3D не задают производительность.', ['Сценарий B: около 551,7 кг/ч пара; давление и перегрев по расчётному отчёту.', 'Нужны расчёт прочности, горение, теплопередача, защита, арматура и проверенная документация.'], [link('Clayton · запрос парогенератора', 'https://www.claytonindustries.com/products/', 'inquiry', ['ALL'], 'Промышленные агрегаты; размещение в ЗАЗ не подтверждено.'), *metal]),
 'CND': ('custom','Готовые блоки под показанный объём не найдены. Теплоотвод текущей внутренней компоновки не подтверждён.', ['Сценарий B: около 358 кВт тепла к отводу.', 'Нужны геометрия, расход воздуха, кривые вентиляторов, противодавление и крепления.'], [link('Kelvion · воздушные паровые конденсаторы', 'https://www.kelvion.com/products/heat-rejection-heat-recovery-solutions/air-cooled-condensers', 'inquiry', ['ALL'], 'Промышленный каталог для запроса, не готовый автомобильный блок.'), link('ebm-papst · подбор осевых вентиляторов', 'https://www.ebmpapst.com/de/en/products/axial-fans.html', 'catalogue', ['ALL'], 'Типоразмер и рабочая точка не выбраны.'), *metal]),
 'PMP': ('candidate','Заводской CAD Cat 5CP2120W.3000; именно высокотемпературное исполнение нужно указать в заказе.', ['Базовый 5CP2120W не равен исполнению .3000.', 'В проекте предел воды 82 °C по заводским данным; проверить горячий подпор, кавитацию, привод и резьбы.'], [link('Cat Pumps · 5CP2120W.3000, запрос предложения', 'https://www.catpumps.com/products/pumps/5cp-plunger-pump-high-temp-5cp2120w3000', 'inquiry', ['ALL'], 'Страница конкретного заводского исполнения.'), link('Cat Pumps NL · поставщик серии 5CP2120W', 'https://www.catpumps.nl/nl/catpumps-5cp2120w.html', 'catalogue', ['EU'], 'Уточнить .3000; данные температуры сверить с заводом.'), link('Cat Pumps · поиск дистрибьютора', 'https://www.catpumps.com/find-distributor', 'inquiry', ['ALL']), link('Cat Pumps TB002 · горячая подача', 'https://www.catpumps.com/sites/default/files/2025-12/TB002_B.pdf', 'documentation', ['ALL'])]),
 'BRN': ('candidate','Компактный дизельный ориентир Riello G10, 54–120 кВт. Точное исполнение, камера и автомобильное применение требуют проверки.', ['305×369×262 мм — размерный ориентир каталога, не заводской CAD.', 'Проверить питание, головку, противодавление камеры, диапазон нагрузки и дымосос.'], [link('Riello · каталог G10 и контакты для подбора','https://www.riello.com/international/files/catalogo-pdf/riello_products_catalogue_international-markets_process_burners_eng.pdf','documentation',['ALL']), link('Riello · выбор горелки и поставщика','https://www.riello.com/international/products/burners','catalogue',['ALL'])]),
 'GBX': ('retained','Сохраняем штатную КПП. Покупка нужна только для ремонта; форма в 3D условная.', ['Проверить допустимый момент, передаточные числа, состояние и сопряжение нового привода.'], parts),
 'BODY': ('retained','Сохраняем исходный кузов. Игровая модель не подтверждает толщины, внутренние зазоры и точки крепления.', ['Двойной клик выбирает конкретную видимую панель, колесо, стекло или предмет салона.', 'Купить замену можно после сверки заводского номера и обмеров.'], parts),
 'SUSP': ('retained','Сохраняем штатную подвеску; показанные размеры предварительные.', ['Для запасной детали сверить узел, сторону и заводской номер.', 'Допустимость новых осевых нагрузок и состояние подвески требуют проверки.'], parts),
 'WTR': ('choice','Холодная подпиточная вода. Можно подобрать готовый бак или заказать по проверенным обмерам.', ['Проектный наружный объём около 39,6 л; полезный не более 31,7 л при допущении 0,8.', 'Каталожный бак не имеет автоматически форму и размеры показанной модели.'], [link('VETUS · готовые баки питьевой воды', 'https://webshop.vetus.com/en/products/fresh-water-systems/tanks-for-drinking-water', 'catalogue', ['EU'], 'Только для холодной подпитки после проверки исполнения.'), link('VETUS · гибкие баки воды', 'https://webshop.vetus.com/en/products/fresh-water-systems/flexible-drinking-water-tanks', 'catalogue', ['EU'], 'Нужны опора, фиксация и защита от горячих поверхностей.'), *metal]),
 'RCV': ('custom','Горячий питательный резервуар: обычный пластиковый бак холодной воды не выбран как замена.', ['Конденсат в расчёте около 78 °C; насос допускает до 82 °C по использованным данным.', 'Проектный наружный объём около 56,9 л. Нужны полезный объём, подпор, деаэрация и опоры.'], [*metal, link('Cat TB002 · требования к горячей подаче', 'https://www.catpumps.com/sites/default/files/2025-12/TB002_B.pdf', 'documentation', ['ALL'])]),
 'FUE': ('choice','Выбрать готовый топливный бак с подтверждёнными параметрами либо заказать специальный.', ['Проектный наружный объём около 22,3 л; бак VETUS 25 л не считается подходящим по размерам.', 'Проверить топливо, крепления, вентиляцию, герметичность и расположение относительно нагрева.'], [link('VETUS · готовые дизельные баки', 'https://webshop.vetus.com/en/products/fuel-systems/tanks-for-diesel-fuel', 'catalogue', ['EU'], 'Сначала выбрать изделие и перенести его реальные размеры.'), *metal]),
 'ELE': ('custom','Собирается из покупного корпуса, датчиков, автоматики и силовых устройств после разработки схемы.', ['Корпус 100×120×150 мм — показанный резерв, достаточность не подтверждена.', 'Питание, токи, независимая защитная цепь, давление/температура/уровень и автозапуск ещё не специфицированы.'], electric),
 'MOTOR': ('choice','Готовый мотор и передача пока не выбраны; показанная форма условная.', ['Подобрать по реальной мощности насоса, оборотам, напряжению, режиму работы и пусковым токам.', 'Заменить условный габарит CAD выбранного двигателя.'], [link('WEG · двигатели W22, каталог поставщика', 'https://weg-russia.ru/catalog/w22', 'catalogue', ['RU']), link('WEG · W22, европейские исполнения', 'https://static.weg.net/medias/downloadcenter/h6b/h66/WEG-w22-three-phase-induction-motors-european-market-50025712-brochure-english-web.pdf', 'documentation', ['ALL']), *electric[:1]]),
 'BOOST': ('choice','Готовый подпорный насос и фильтр подбираются по горячему входу Cat, не по внешнему сходству.', ['Проверить температуру около 78 °C, расход, напор, кавитационный запас и потери фильтра.', 'Показанный небольшой резерв не означает, что насос Grundfos в него поместится.'], [link('Grundfos · CME, запрос исполнения', 'https://www.grundfos.com/gb/en/products/products/cm-cme/cme', 'inquiry', ['ALL'], 'Промышленная серия; размеры и рабочая точка ещё не выбраны.'), *tube[:1]]),
 'SEP': ('custom','Условный приёмник аварийного сброса; сепаратор влаги в рабочем паропроводе не является заменой.', ['Требуется расчёт двухфазного сброса, отвода тепла, безопасного выхода и полного расхода.', 'Предохранительный клапан выбирается по утверждённому парогенератору.'], [*metal, link('Spirax Sarco · предохранительные клапаны', 'https://www.spiraxsarco.com/-/media/spiraxsarco/international/documents/en/sb/safety-valves-overview-sb-s13-60-en.ashx?rev=c0693952348948d09c9afc4ff94e3a3e', 'documentation', ['ALL'], 'Каталог для подбора, не выбранный клапан.')]),
 'MOUNTS': ('custom','Рамы и крепления проектируются по нагрузкам и реальным силовым точкам кузова.', ['Опоры в 3D касаются игрового пола; это не доказательство прочности крепления.', 'Сечения, марка, болты, изоляторы, усталость и сварка ещё не рассчитаны.'], [*metal, *electric[:1]]),
 'SHIELD': ('custom','Тепловые и пожарные перегородки из листа и специализированной изоляции по расчёту.', ['Проверить температуры, зазоры, герметичность и прохождение труб.', 'Показанные плоскости не задают проверенную огнестойкость конструкции.'], [*metal, *insulation]),
 'ADAPTER': ('custom','Сопряжение паровой машины со штатной КПП — отдельный проект муфты и адаптера.', ['Нужны соосность, реальные валы, момент, вибрация, крепление и передаточное отношение.', 'Каталог муфт не заменяет расчёт автомобильного привода.'], [link('MISUMI · конфигуратор муфт', 'https://de.misumi-ec.com/vona2/mech/M1000000000/M1001000000/M1001070000/', 'catalogue', ['EU'], 'Тип, диаметр и допустимый момент не выбраны.'), *metal]),
 'DUCTS': ('custom','Воздуховоды изготавливаются после подтверждения схемы охлаждения.', ['Свободное сечение текущего варианта недостаточно подтверждено для отвода 358 кВт.', 'Нужны аэродинамика, водоотвод, защита от горячих зон и доступ к ремонту.'], [*metal, link('ebm-papst · осевые вентиляторы', 'https://www.ebmpapst.com/de/en/products/axial-fans.html', 'catalogue', ['ALL'])]),
}

def number(x): return 'не задано' if x is None else f'{x:.2f}'.rstrip('0').rstrip('.').replace('.', ',')

def main():
    native=json.loads((ROOT/'models/steam-internal-assembly.json').read_text())
    entries={e['id']:e for e in native['entries']}
    routes=json.loads((ROOT/'pipe-engineering.json').read_text())['routes']
    for r in routes:
        params=[f"ID {number(r['inside_id_mm'])} / OD {number(r['od'])} мм; стенка {number(r['wall_mm'])} мм.", f"Ось трассы {number(r['centerline_length_m'])} м; минимальный радиус {number(r['bend_radius_mm'])} мм."]
        if r['id'].startswith('WIRE'):
            specs[r['id']]=('custom','Показана трасса жгута, а не спецификация проводов.',[f"Наружный Ø оболочки {number(r['od'])} мм; ось {number(r['centerline_length_m'])} м; радиус {number(r['bend_radius_mm'])} мм."]+['Диаметр оболочки не задаёт сечение проводников; питание и токи ещё не рассчитаны.'],wires)
        else:
            if r.get('connected') is False:params.append('В 3D показан только неподключённый выход. Длина короткого участка не является спецификацией полного дымового канала.')
            params += [f"ArmaGel HT {number(r['insulation_mm'])} мм + кожух {number(r['jacket_mm'])} мм; полный Ø {number(r['outer_envelope_mm'])} мм.", 'Это геометрические кандидаты: марка, прочность при давлении/температуре, фасонные части, опоры и компенсация расширения не подобраны.']
            ls = [*tube]
            if r['insulation_mm']>0: ls += insulation
            if r['jacket_mm']>0: ls += jacket
            if r['fluid'] in ('fuel','water'): ls += [link('Swagelok · шланги и гибкие трубки', 'https://products.swagelok.com/en/all-products/hoses-flexible-tubing/c/700?plp=true', 'catalogue', ['ALL'], 'Исполнение для конкретной среды, давления и температуры не выбрано.', 'pipe')]
            specs[r['id']]=('custom','Трасса собирается из подобранных труб/отводов, арматуры, опор и изоляции.',params,ls)
    names={**{k:e['name'] for k,e in entries.items() if e.get('name')},'BODY':'Кузов ЗАЗ-968М · узлы исходной модели','SUSP':'Штатная подвеска · 50 узлов','PMP':'Cat Pumps 5CP2120W.3000','BRN':'Компактный дизель · ориентир G10'}
    assert set(names)==set(specs),(set(names)-set(specs),set(specs)-set(names))
    components={}
    for k,(status,description,requirements,links) in specs.items():
        components[k]=dict(id=k,name=names[k],status=status,description=description,requirements=requirements,links=links)
        if k in entries: components[k]['concept_size_mm']=[round(x,2) for x in entries[k]['size_mm']]
    data=dict(version=1,checked_on='2026-10-08',policy='Ссылка на товар, каталог или изготовителя не подтверждает совместимость, наличие, доставку или возможность дорожной регистрации. Цены не фиксируются. Финляндия / ЕС и Россия — регионы поставщиков, не гарантия доставки.',components=components)
    (ROOT/'component-purchases.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
    print(f'Procurement register: {len(components)} assemblies, {sum(len(x["links"]) for x in components.values())} attributed links')

if __name__=='__main__': main()
