from html import escape
import re

def content(d):
    def f(x,n=1): return f'{x:,.{n}f}'.replace(',', '\u202f').replace('.', ',')
    def formula(title,equation,sub):
        return f'<article class="thermal-formula"><h3>{title}</h3><code>{equation}</code><p>{sub}</p></article>'
    rows=[];panels=[]
    for r in d['rows']:
        g,t=r['geometry'],r['thermal'];D=g['bore_mm'];safe=not any(not p.get('connected') for p in g['conflicts'])
        internal=min(x['barrel_envelope_clearance_mm'] for x in g['internal_pipe_screen'])
        rows.append(f'<tr><td>Ø{D} × 45</td><td>{f(t["geometry"]["swept_L"],3)}</td><td>{f(t["crank_rpm"],0)}</td><td>{f(t["torque_output_Nm"],1)}</td><td>{f(t["shaft_kW"],2)}</td><td>{"Выпуск требует доработки" if internal<0 else "Без внешних пересечений" if safe else "Есть пересечение"}; до труб цилиндров ≥{f(internal,1)} мм*</td></tr>')
        for case,label in [('working','Обороты при50 кВт тепла'),('overspeed','Исследовательский сценарий2600 об/мин')]:
            s=r[case+'_strength'];k=s['assumptions'];loads=s['design_loads'];p=s['proposed'];j=s['proposed_small_joint'];sl=s['proposed_slave_joint'];fork=s['master_fork'];c=s['cylinder']
            sections=[('Шток поршня · гипотеза Kt=2','Ø9,6',f(s['piston_rod']['current_assumed_Kt_stress_MPa'],0),'Ø14; переподбор сальника и поршня',f(s['piston_rod']['proposed_assumed_Kt_stress_MPa'],1)),('Щека коленвала · гипотеза Kt=2','15 × 5',f(s['crank_web']['current_assumed_Kt_stress_MPa'],0),'80 × 25; две щеки',f(s['crank_web']['proposed_assumed_Kt_stress_MPa'],1)),('Выходной вал · изгиб + кручение','Ø12,5',f(s['current']['shaft_vm_MPa'],0),'Ø45; вылет15 мм',f(p['shaft_vm_MPa'],1)),('Общая шатунная шейка','Ø15; одна щека',f(s['current']['actual_cantilever_crankpin_vm_MPa'],0),'Ø40; две щеки, пролёт32 мм',f(p['crankpin_vm_MPa'],1)),('Палец крейцкопфа · изгиб + срез','Ø4',f(s['current_small_joint']['pin_vm_MPa'],0),'Ø16; вилку тоже переработать',f(j['pin_vm_MPa'],1)),('Палец прицепного шатуна · изгиб + срез','Ø6',f(s['current_slave_joint']['pin_vm_MPa'],0),'Ø16',f(sl['pin_vm_MPa'],1)),('Шатун · нетто-сечение и гипотеза Kt=2,5','10 × 4; отверстиеØ4,4',f(s['current_small_joint']['net_section_with_assumed_Kt_MPa'],0),'36 × 12; отверстиеØ16,4',f(j['net_section_with_assumed_Kt_MPa'],1)),('Вилка главного шатуна · перемычка у пальца','Щёки3; наружныйØ64',f(fork['current_assumed_Kt_stress_MPa'],0),'Щёки12; наружныйØ120; шарнирыR40',f(fork['proposed_assumed_Kt_stress_MPa'],1))]
            sectionrows=''.join(f'<tr><td>{name}</td><td>{old}</td><td>{oldstress}</td><td>{new}</td><td>{newstress}</td></tr>' for name,old,oldstress,new,newstress in sections)
            cards=''.join([
                formula('Обычный рабочий объём','V = 7 · πD²S / 4',f'7 × π × ({D}/1000)² × 0,045 / 4 ×1000 = <strong>{f(t["geometry"]["swept_L"],3)} л</strong>. Для двойного действия объём двух сторон за оборот {f(t["geometry"]["double_L"],3)} л.'),
                formula('Сила пара на ходе к центру','FА = (pА − pокр)·А − (pB − pокр)·(А − Ашт)',f'(10−1)×0,1×π×{D}²/4 − (1,2−1)×0,1×π×({D}²−9,6²)/4 = <strong>{f(s["working_force_A_N"],0)} Н</strong>. Все давления указаны абсолютными,1 бар=0,1 Н/мм². В обратную сторону {f(s["working_force_B_N"],0)} Н.'),
                formula('Масса и инерция','m = ρст·(Ап·tп + Ашт·Lшт) + mдоп; a = d²R/dθ² · (2πn/60)²; Fин = m·a',f'7850×[π×({D}/1000)²/4×0,0075 + π×0,0096²/4×0,0675]+0,35 = {f(s["mass_reciprocating_each_kg"],3)} кг/цилиндр. При n={f(s["rpm"],0)} об/мин: max|a|≈{f(s["peak"]["acceleration_m_s2"],0)} м/с²; max|Fин|≈{f(s["mass_reciprocating_each_kg"]*s["peak"]["acceleration_m_s2"],0)} Н. Добавка0,35 кг — гипотеза, её надо заменить массами нового CAD.'),
                formula('Передача усилия общей шейке','Nᵢ = Fᵢ/(uᵢ·wᵢ); ΣMшейка = 0; Rшейка = −ΣF; T = rкр × ΣF',f'720 положений для иллюстративной диаграммы,180 положений×128 комбинаций граничных сил при15 бар abs для тяжёлого сценария. Получено Rmax≈{f(s["independent_force_bound"]["reaction_N"],0)} Н и |T|max≈{f(s["independent_force_bound"]["torque_Nm"],1)} Н·м. После принятого множителя1,5: <strong>{f(loads["crankpin_N"]/1000,1)} кН; {f(loads["torque_Nm"],0)} Н·м</strong>. Это оценка нагрузок; её нельзя выдавать за номинальный момент теплового расчёта.'),
                formula('Условный экран напряжений','[σ] = Re / nзап; σэкв = √(σизг² + 3τ²)',f'Для подбора приняты42CrMo4+QT, консервативные Re=550 МПа при комнатной температуре и nзап=5: [σ]=550/5=<strong>110 МПа</strong>. Свойства металла наших деталей неизвестны; для250 °C и −25 °C этот предел не подтверждён.'),
                formula('Вал нового сечения','M = R·l; σизг = 32M/(πd³); τ = 16T/(πd³)',f'M={f(loads["crankpin_N"],0)}×15={f(loads["crankpin_N"]*15,0)} Н·мм; σизг=32×{f(loads["crankpin_N"]*15,0)}/(π×45³)={f(p["shaft_bending_MPa"],1)} МПа. τ=16×{f(loads["torque_Nm"],1)}×1000/(π×45³)={f(p["shaft_torsion_MPa"],1)} МПа. σэкв={f(p["shaft_vm_MPa"],1)} МПа; условный запас к Re={f(p["shaft_room_yield_margin"],1)}. Надрезы, крутильные колебания и галтелевые напряжения отдельно.'),
                formula('Новые пальцы и нетто-сечение шатуна','τ = F/(2·πd²/4); Mпал = F·L/4; σнетто = Kt·F/[(b−dотв)·t]',f'Для пальца крейцкопфа F={f(loads["joint_N"],0)} Н; d=16 мм; L=12+6=18 мм; σэкв={f(j["pin_vm_MPa"],1)} МПа. Для шатуна2,5×{f(loads["joint_N"],0)}/[(36−16,4)×12]={f(j["net_section_with_assumed_Kt_MPa"],1)} МПа. Kt=2,5 — чувствительность к надрезу, а не результат FEA.'),
                formula('Потеря устойчивости шатуна','PЭйлер = π²EI/(KL)²; I = b·t³/12',f'Для шарнирных концов K=1: π²×210000×(36×12³/12)/150² = {f(j["euler_load_N"],0)} Н. Запас PЭйлер/F≈{f(j["buckling_margin"],1)}. Это прямой идеальный стержень; эксцентриситет, отверстия и горячие свойства требуют уточнения.'),
                formula('Гладкая стенка цилиндра и крышка','σθ(ri) = Δp·(ro²+ri²)/(ro²−ri²); σкрыш,полоса = 3Δp·(a/t)²',f'Δp=(15−1)×0,1=1,4 МПа; ri={f(D/2)}, ro={f(D/2+5)} мм: σθ={f(c["wall_hoop_MPa"],1)} МПа. Крышка2,5 мм, полосовая модель с пролётомD:3×1,4×({f(D/2)}/2,5)²={f(c["head_solid_strip_MPa"],0)} МПа. Для110 МПа нужно t≥{f(c["head_solid_minimum_mm"],1)} мм до учёта отверстий и крепежа. Первая заготовка под расчёт —8 мм; её достаточность не доказана.'),
                formula('Подшипник скольжения: давление и скорость','p = R/(d·l); v ≤ πdn/60; pV = p·v',f'p={f(loads["crankpin_N"],0)}/(40×24)={f(p["crankpin_bearing_MPa"],1)} МПа; v≤π×0,040×{f(s["rpm"],0)}/60={f(s["bearing"]["speed_upper_m_s"],2)} м/с; pV≤{f(s["bearing"]["pv_upper_MPa_m_s"],1)} МПа·м/с. Сухой GGB DU с пределом1,8 сюда не подходит. Предел скорости5 м/с в масляном режиме — отдельное ограничение, а не разрешение этого pV. Нужен расчёт масляного подшипника и теплоотвода.'),
            ])
            panels.append(f'<section class="bore-panel" data-bore="{D}" data-case="{case}"'+('' if D==60 and case=='working' else ' hidden')+f'><h2>Ø{D} × 45 · {label}</h2>{cards}<h3>Сечения нынешнего механизма и предварительный подбор усиления</h3><p>Номинальные упругие напряжения в МПа. Значения выше предела текучести означают провал модели упругой детали; это не реальные напряжения разрушившегося металла. Новый силовой механизм в3D ещё не создан.</p><div class="table-scroll"><table><thead><tr><th>Узел</th><th>Сейчас</th><th>Расчёт, МПа</th><th>Гипотеза усиления</th><th>Расчёт, МПа</th></tr></thead><tbody>{sectionrows}</tbody></table></div><p>Вилка Ø120 с пальцамиR40 требует нового решения кинематики вместо нынешнихR24. Отдельные сечения проверены под нагрузками старой кинематики; полного подтверждения усиленной конструкции нет. Стойки, поддон, крепления к кузову, болты, галтелевые переходы, балансировка и температурный ресурс ещё не рассчитаны.</p></section>')
    limits=''.join('<li>'+escape(x)+'</li>' for x in d['limitations'])
    sources=''.join('<li><a href="'+escape(x['url'],quote=True)+'" target="_blank" rel="noopener">'+escape(x['title'])+'</a></li>' for x in d['sources'])
    text = f'''<section class="page-hero"><span class="eyebrow">Увеличение цилиндров ·10 октября2026</span><h1>Диаметр отдельно от хода. Прочность отдельно от посадки.</h1><p>При ходе45 мм увеличенные цилиндры Ø50–100 помещаются в наружный габарит570 ×562 ×375 мм после переразводки камер B по предоставленной сетке. Для них перенесён выпускной порт распределителя на внутреннюю грань и изменены семь выпускных труб. Для Ø100 консервативный экран дополнительно выявил касание оболочки выпускной трубы с изоляцией цилиндров: его надо устранить. Силовой механизм пока прежний и не проходит принятый прочностной экран.</p><p>Следующий кандидат для нового силового CAD: <strong>семь Ø60 ×45 мм, рабочий объём0,891 л</strong>. При50 кВт тепла в паре: примерно578 об/мин и3,35 кВт на валу до вспомогательных агрегатов. Увеличение диаметра не создаёт дополнительного тепла.</p><div class="hero-actions"><a class="button" id="boreModelLink" href="assembly.html?component=ENG&amp;cylinder-bore=60">Посмотреть Ø60 в кузове</a><a class="button secondary" id="boreMechanismLink" href="assembly.html?component=ENG&amp;mechanics=1&amp;cylinder-bore=60">Посмотреть прежний механизм</a><a class="button secondary" href="engine-strength-report.pdf">Скачать расчёт PDF</a></div></section>
<p class="sim-preflight"><strong>Аудит парораспределения:</strong> прежние коробки были пустыми, без клапанов. В 3D добавлены четыре раздельно запираемых функциональных прохода. Внутренние линии условные; привод, размеры клапанов и уплотнения не рассчитаны. Объём камерных трубок теперь показан отдельно, но прежние оценки оборотов, момента и КПД не решают наполнение и расширение с этим объёмом. <a href="assembly.html?component=ENG#engineDistributionPanel">Открыть камеры, клапаны и направления потока →</a></p><section><h2>Сравнение при одинаковом расходе пара</h2><p>10 бар abs,250 °C; противодавление1,2 бар; шток9,6 мм; ход45 мм; отсечка0,30; наполнение0,85; ηиз=0,50 и ηмех=0,90 — прежние гипотезы проекта.</p><div class="table-scroll"><table><thead><tr><th>Цилиндры</th><th>Объём, л</th><th>Об/мин</th><th>Момент, Н·м</th><th>На валу, кВт</th><th>Геометрический экран</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><p>*Только до оболочек цилиндров, с консервативным диаметром изоляции труб и исключёнными штатными конечными участками камер. Это не минимальный зазор до всех деталей. До кузова примерно18 мм, до статической подвески ≥50 мм. Пересечения торцов общих подающих/выпускных труб со штатными штуцерами отмечены отдельно. Три прежних конфликта труб всей сборки сохраняются. Усиленный механизм, движение подвески и тепловое расширение в этот геометрический результат не входят.</p></section>
<section class="strength-controls"><label>Диаметр цилиндра <select id="strengthBore">{''.join(f'<option value="{r["geometry"]["bore_mm"]}"'+(' selected' if r['geometry']['bore_mm']==60 else '')+f'>Ø{r["geometry"]["bore_mm"]} ×45 мм</option>' for r in d['rows'])}</select></label><label>Режим проверки <select id="strengthCase"><option value="working">Обороты при50 кВт тепла</option><option value="overspeed">Сценарий2600 об/мин</option></select></label><p>Оба режима дополнительно проверяются при граничной нагрузке15 бар abs ×1,5. Это заданные сценарии исследования, а не допустимые режимы эксплуатации.</p></section>
{''.join(panels)}<section><h2>Усталость, температура и реальный ресурс</h2><p>Два года×365 дней×50 км/день =36500 км. При условных50 км/ч двигатель работает730 ч плюс прогревы. Для Ø60 при578 об/мин это730×60×578≈25,3 млн оборотов. Эта цифра — число циклов, а не доказанный ресурс. Нужны действительная частота вращения по передачам, история давлений и температур, S–N, свойства при нагреве, состояние поверхности и надрезы.</p><p>Для статического сравнения температура пара250 °C не была ошибочно назначена температурой всех валов. Температуры металла должны следовать отдельному тепловому расчёту. При −25 °C надо подтвердить вязкость масла, ударную вязкость материала, зазоры и защиту воды от замерзания. Значения из каталога при20 °C этого не подтверждают.</p><details><summary>Границы этого расчёта</summary><ul>{limits}</ul></details></section><section><h2>Исходные данные и проверяемые материалы</h2><div class="hero-actions"><a href="engine-strength-study.json">Полный расчёт JSON</a><a href="engine-bore-fit.json">Проверка геометрии JSON</a><a href="engine-strength-checks.json">Независимые проверки</a><a href="engine-strength-model.js">Формулы и расчётный модуль</a><a href="build_engine_strength.mjs">Повторить расчёт</a></div><ul>{sources}</ul><p><a href="fitted-engine.html">Основной вариант Ø40 ×45</a> · <a href="aging.html">Модель старения и ресурс</a></p></section>'''

    return re.sub(r">([^<]*)<", lambda m: ">"+re.sub(r"(?<=[А-Яа-яЁё])(?=[0-9])|(?<=[0-9])(?=[А-Яа-яЁё])", " ", m[1])+"<", text)
