import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {createCompactRadial} from './compact-radial-geometry.js';
import {compactGeometry as K} from './compact-radial-model.js';
import {auditPackaging} from './packaging-audit.js';
const $=id=>document.getElementById(id),f=(v,d=1)=>v.toLocaleString('ru-RU',{maximumFractionDigits:d});
const scene=new T.Scene();scene.background=new T.Color('#0b1117');const camera=new T.PerspectiveCamera(42,1,1,20000);camera.up.set(0,0,1);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;$('radialViewport').append(renderer.domElement);$('radialFallback').hidden=true;
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.rotateSpeed=-1;
scene.add(new T.HemisphereLight(0xe5f2ff,0x3e4850,2.5));for(const p of [[3200,-1200,2300],[2800,1700,1000]]){const l=new T.DirectionalLight(0xffffff,2.5);l.position.fromArray(p);scene.add(l);}
const engine=createCompactRadial();engine.root.position.fromArray(K.origin);scene.add(engine.root);
const car=new T.Group();car.name='Предоставленный кузов и штатные узлы';scene.add(car);let body,stock,gbx,bodyMeta,fit=null,angle=0,flowTime=0,playing=true,selected=0,last=performance.now();
const excluded=o=>{for(let p=o;p;p=p.parent)if(p.userData.viewOnly)return true;return o.userData.collision===false;};
function physicalBox(g){g.updateWorldMatrix(true,true);const b=new T.Box3();g.traverse(o=>{if(o.isMesh&&!excluded(o)){if(o.userData.tightBounds){const a=o.geometry.attributes.position,v=new T.Vector3();for(let i=0;i<a.count;i++)b.expandByPoint(v.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld));}else{o.geometry.computeBoundingBox();b.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));}}});return b;}
function showBounds(){const b=physicalBox(engine.core),s=b.getSize(new T.Vector3()),inside=b.min.toArray().every((x,i)=>x>=K.reserveMin[i])&&b.max.toArray().every((x,i)=>x<=K.reserveMax[i]);$('compactBounds').textContent=`Текущая полная геометрия двигателя без стоек до пола: ${s.toArray().map(x=>f(x,1)).join(' × ')} мм. ${inside?'В пределах прежнего резерва600×500×500 мм.':'Выходит за прежний резерв; требуется переработка.'} Стойки до пола проверяются отдельно.`;return {min_mm:b.min.toArray(),max_mm:b.max.toArray(),size_mm:s.toArray(),inside_reserve:inside};}
function bodyPresentation(){if(body)body.traverse(o=>{if(o.isMesh)for(const m of [].concat(o.material)){m.transparent=true;m.opacity=Number($('compactOpacity').value);m.depthWrite=m.opacity>.9;m.side=T.DoubleSide;m.clippingPlanes=$('compactSlice').checked?[new T.Plane(new T.Vector3(0,0,-1),680)]:[];}});}
function view(){const mode=$('compactView').value,isolated=['engine','top'].includes(mode);car.visible=!isolated;engine.mounts.visible=!isolated;engine.contacts.visible=!isolated;if(stock)stock.visible=$('compactStock').checked;if(gbx)gbx.visible=$('compactStock').checked;
 if(mode==='car'){controls.target.set(1880,0,600);camera.position.set(5900,-4200,3200);}else{controls.target.set(...(mode==='top'?[3210,0,580]:[3210,0,550]));camera.position.set(...(mode==='top'?[3210,0,2050]:[3920,-780,1100]));}controls.update();}
new ResizeObserver(()=>{const w=$('radialViewport').clientWidth,h=$('radialViewport').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe($('radialViewport'));
for(let i=0;i<7;i++){const o=document.createElement('option');o.value=i;o.textContent='Цилиндр '+(i+1);$('compactCylinder').append(o);}
const phase={admission:'впуск',expansion:'закрытое расширение',release:'начало выпуска',exhaust:'выпуск'};
function status(states){const p=states[selected];$('compactStatus').textContent=`Цилиндр ${selected+1}: A — ${phase[p.A.phase]}, ${f(p.A.volume_cm3,2)} см³; B — ${phase[p.B.phase]}, ${f(p.B.volume_cm3,2)} см³. Выходной вал ${f(angle*180/Math.PI%360,1)}°.`;$('compactAngle').value=String(angle*180/Math.PI%360);}
$('compactView').onchange=view;$('compactStock').onchange=view;$('compactOpacity').oninput=bodyPresentation;$('compactSlice').onchange=bodyPresentation;$('compactCutaway').onchange=()=>engine.cutaway($('compactCutaway').checked);
function pause(){playing=false;$('compactPlay').textContent='Воспроизвести';$('compactPlay').setAttribute('aria-pressed','false');}
$('compactPlay').onclick=()=>{playing=!playing;$('compactPlay').textContent=playing?'Пауза':'Воспроизвести';$('compactPlay').setAttribute('aria-pressed',String(playing));};
$('compactAngle').oninput=()=>{pause();angle=Number($('compactAngle').value)*Math.PI/180;status(engine.update(angle,flowTime,camera,$('compactArrows').checked));};$('compactCylinder').onchange=()=>{selected=Number($('compactCylinder').value);status(engine.update(angle,flowTime,camera,$('compactArrows').checked));};
const ray=new T.Raycaster();renderer.domElement.ondblclick=e=>{const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2(2*(e.clientX-r.left)/r.width-1,1-2*(e.clientY-r.top)/r.height),camera);for(const h of ray.intersectObject(engine.root,true)){if(excluded(h.object))continue;let p=h.object;while(p&&p.userData.cylinder===undefined)p=p.parent;if(p){selected=p.userData.cylinder;$('compactCylinder').value=selected;pause();$('compactSelection').textContent='Выбрано: цилиндр '+(selected+1)+' · '+h.object.name;status(engine.update(angle,flowTime,camera,$('compactArrows').checked));break;}}};
let fallback=false;function fullSync(){const active=document.fullscreenElement===$('radialViewer')||fallback;$('radialViewer').classList.toggle('radial-expanded',fallback);document.body.classList.toggle('radial-fullscreen',fallback);$('compactFullscreen').textContent=active?'Выйти из полного экрана':'На весь экран';$('compactFullscreen').setAttribute('aria-pressed',String(active));}
$('compactFullscreen').onclick=async()=>{if(fallback)fallback=false;else if(document.fullscreenElement===$('radialViewer'))await document.exitFullscreen();else try{await $('radialViewer').requestFullscreen();}catch{fallback=true;}fullSync();};document.addEventListener('fullscreenchange',fullSync);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&fallback){fallback=false;fullSync();}});
function mergedCollider(g,name){g.updateWorldMatrix(true,true);const geometries=[];g.traverse(o=>{if(!o.isMesh||excluded(o))return;const a=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();for(const n of Object.keys(a.attributes))if(!['position','normal'].includes(n))a.deleteAttribute(n);if(!a.attributes.normal)a.computeVertexNormals();a.applyMatrix4(o.matrixWorld);geometries.push(a);});const merged=mergeGeometries(geometries,false),m=new T.Mesh(merged,new T.MeshBasicMaterial());m.name=name;const root=new T.Group();root.add(m);for(const g of geometries)g.dispose();return root;}
function fitText(v){const p=v.audit.parts,body=p.flatMap(p=>p.body_intersections),stock=p.flatMap(p=>p.stock_intersections);return `Габарит: ${v.bounds.size_mm.map(x=>f(x,1)).join(' × ')} мм. ${v.bounds.inside_reserve?'В резерве.':'Выход за резерв.'} Пересечений с поверхностями кузова: ${body.length}; со статической подвеской: ${stock.length}. Минимальный зазор двигателя до кузова: ${f(p[0].clearance_mm)} мм${p[0].clearance_is_lower_bound?' или больше':''}. Контакты4 площадок с полом — намеренные. Реальная посадка и движение подвески не подтверждены.`;}
function floorContactProof(){body.updateWorldMatrix(true,true);const floor=[];body.traverse(o=>{if(o.isMesh&&o.name.includes('Plane113'))floor.push(o);});const ray=new T.Raycaster(),result=[];engine.contacts.traverse(o=>{const k=o.userData.floorContact;if(!k)return;const samples=[];for(const dx of [-k.pad_half_mm,0,k.pad_half_mm])for(const dy of [-k.pad_half_mm,0,k.pad_half_mm]){const [x,y,z]=k.anchor_mm,expected=z+k.slopes[0]*dx+k.slopes[1]*dy;ray.set(new T.Vector3(x+dx,y+dy,800),new T.Vector3(0,0,-1));const hits=ray.intersectObjects(floor,true),actual=hits.length?hits.reduce((a,h)=>Math.abs(h.point.z-expected)<Math.abs(a-expected)?h.point.z:a,hits[0].point.z):null;samples.push({dx_mm:dx,dy_mm:dy,pad_bottom_z_mm:expected,floor_z_mm:actual,error_mm:actual===null?null:Math.abs(actual-expected)});}result.push({...k,samples,max_error_mm:Math.max(...samples.map(x=>x.error_mm??Infinity)),geometric_contact_confirmed:samples.every(x=>x.error_mm!==null&&x.error_mm<.01)});});return result;}
async function audit(){if(!body||!stock)throw Error('Дождитесь загрузки кузова и подвески');pause();angle=0;engine.update(0,0);const fullBody=body.clone(true);fullBody.visible=true;fullBody.traverse(o=>{if(o.isMesh)o.visible=!['source-stock','rear-seat'].includes(o.userData.bodyGroup);});const fullStock=stock.clone(true);fullStock.visible=true;
 const core=mergedCollider(engine.core,'Двигатель с полными габаритами'),posts=mergedCollider(engine.mounts,'Стойки над полом');const a=await auditPackaging({root:fullBody},[{id:'COMPACT_ENGINE',root:core},{id:'POSTS',root:posts,support:true},{id:'SUSP',root:fullStock,retainedStock:true}],{name:'Компактная звезда в предоставленном кузове',detailed:true,all_equipment_inside_required:true,geometry_clearance_rule_mm:50,removed_body_groups:['source-stock','rear-seat'],open_issues:['Игровая геометрия кузова и статическая гипотеза подвески; прочность, точная КПП, ход подвески, тепловые/сервисные зазоры не подтверждены.']});
 fit={status:'geometry_screen_only',bounds:showBounds(),audit:a,contacts:floorContactProof(),body_source:bodyMeta.source,body_sha256:bodyMeta.glb_sha256,gearbox_axis_verified:false,complete_vehicle_verified:false};$('compactFitStatus').textContent=fitText(fit);core.traverse(o=>o.geometry?.dispose());posts.traverse(o=>o.geometry?.dispose());return fit;
}
$('compactAudit').onclick=async()=>{const b=$('compactAudit');b.disabled=true;$('compactFitStatus').textContent='Проверяю все поверхности, включая закрытую крышку отсека…';try{await audit();}catch(e){$('compactFitStatus').textContent='Проверка не выполнена: '+e.message;}finally{b.disabled=false;}};
async function exportModel(full=false){const all=new T.Group(),copy=engine.root.clone(true);if(!full)copy.position.set(0,0,0);const removed=[];copy.traverse(o=>{if(o.userData.viewOnly)removed.push(o);});removed.forEach(o=>o.removeFromParent());all.add(copy);if(full){const bodyCopy=body.clone(true),drop=[];bodyCopy.traverse(o=>{if(['source-stock','rear-seat'].includes(o.userData.bodyGroup))drop.push(o);});drop.forEach(o=>o.removeFromParent());all.add(bodyCopy,stock.clone(true));if(gbx)all.add(gbx.clone(true));}all.scale.setScalar(.001);all.rotation.x=-Math.PI/2;all.userData={units:'metres/Y-up',source_units:'mm/Z-up',placement_origin_mm:K.origin,status:'Concept geometry; pressure, material, gearbox and road performance unverified',body_attribution:full?{author:'yatloo',license:'CC BY 4.0',source:bodyMeta.source}:undefined};all.updateWorldMatrix(true,true);return new GLTFExporter().parseAsync(all,{binary:true,onlyVisible:false});}
$('compactExport').onclick=async()=>{const b=$('compactExport');b.disabled=true;try{const data=await exportModel(),a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));a.href=url;a.download='compact-radial-engine.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}catch(e){$('compactStatus').textContent='Ошибка экспорта: '+e.message;}finally{b.disabled=false;}};
view();showBounds();let lastStatus=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.max(0,Math.min(.05,(now-last)/1000));last=now;if(playing){angle=(angle+dt*Math.PI/15)%(Math.PI*2);flowTime+=dt;}controls.update();const states=engine.update(angle,flowTime,camera,$('compactArrows').checked);if(now-lastStatus>200){status(states);lastStatus=now;}renderer.render(scene,camera);}requestAnimationFrame(frame);
try{const loader=new GLTFLoader();[bodyMeta,body,stock]=await Promise.all([fetch('models/zaz-968m-yatloo.json').then(r=>r.json()),loader.loadAsync('models/zaz-968m-yatloo.glb').then(g=>g.scene),loader.loadAsync('models/stock-suspension.glb').then(g=>g.scene)]);for(const o of [body,stock]){o.scale.setScalar(1000);o.rotation.x=Math.PI/2;car.add(o);}body.traverse(o=>{if(o.isMesh&&['source-stock','rear-seat'].includes(o.userData.bodyGroup))o.visible=false;});stock.traverse(o=>{if(o.isMesh&&o.userData.stockGroup)o.position.y=(bodyMeta.registration.stock_registration_z_offsets_mm[o.userData.stockGroup]||0)/1000;});
 const m=new T.MeshStandardMaterial({color:'#6c8596',transparent:true,opacity:.3,wireframe:true});gbx=new T.Mesh(new T.BoxGeometry(500,320,350),m);gbx.name='Штатная КПП · прежний неподтверждённый габарит';gbx.position.set(2730,0,455);car.add(gbx);bodyPresentation();view();
 fetch('compact-radial-fit.json').then(r=>r.ok?r.json():null).then(x=>{if(x?.audit)$('compactFitStatus').textContent=fitText(x);}).catch(()=>{});
 window.compactRadialProject={engine,body,stock,gbx,camera,controls,renderer,scene,audit,exportModel,bounds:showBounds,pause,setAngle(a){pause();angle=a;engine.update(angle,0);},get angle(){return angle;},get fit(){return fit;}};
}catch(e){$('compactFitStatus').textContent='Ошибка загрузки кузова: '+e.message;}
