import {wheelLoads,massItems} from './wheel-loads.js';
const $=id=>document.getElementById(id),fmt=(n,d=2)=>n.toLocaleString('ru-RU',{maximumFractionDigits:d}),el=(t,text)=>{const e=document.createElement(t);if(text!==undefined)e.textContent=text;return e;};
try{const r=await fetch('simulation-data.json');if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json(),items=massItems(data),body=$('massInputs');
 for(const item of items){const tr=el('tr');tr.append(el('th',item.id+' · '+item.name));for(const [key,index]of [['kg',null],['x',0],['y',1],['z',2]]){const td=el('td'),input=el('input');input.type='number';input.step='.01';input.value=index===null?item.kg:item.xyz_m[index];input.setAttribute('aria-label',item.name+' '+key);input.oninput=()=>{if(Number.isFinite(input.valueAsNumber)){if(index===null)item.kg=input.valueAsNumber;else item.xyz_m[index]=input.valueAsNumber;render();}};td.append(input);tr.append(td);}tr.append(el('td',item.source));body.append(tr);}
 function render(){try{const params=Object.fromEntries([...document.querySelectorAll('[data-load-param]')].map(e=>[e.dataset.loadParam,e.valueAsNumber]));const c=wheelLoads(items,params);$('loadSummary').textContent='Масса '+fmt(c.mass_kg,1)+' кг · центр тяжести XYZ '+c.cg_m.map(v=>fmt(v,3)).join(' / ')+' м. '+(c.mass_kg>1200?'Превышен прежний справочный предел полной массы 1200 кг.':'Пределы осей, шин и подвески ещё не подтверждены.');$('loadResults').replaceChildren();for(const w of c.wheels){const row=el('tr');for(const value of [w.name,fmt(w.N,1)+' Н',fmt(w.kg_equivalent,1)+' кг',fmt(w.delta_mm,1)+' мм',fmt(w.wheel_rate_N_m/1000,2)+' кН/м',fmt(w.spring_force_N,1)+' Н',w.front_torsion_moment_Nm===null?'—':fmt(w.front_torsion_moment_Nm,1)+' Н·м',w.lift?'ОТРЫВ: линейное решение недействительно':w.travelExceeded?'Превышен заданный условный запас хода':'Нужны реальные пределы нагрузки'])row.append(el('td',value));if(w.lift||w.travelExceeded)row.className='physics-fault';$('loadResults').append(row);}
 const cards=[['Центр тяжести','xCG = Σ(mᵢxᵢ)/Σmᵢ',items.map(i=>'('+fmt(i.kg,1)+' × '+fmt(i.xyz_m[0],3)+')').join(' + ')+'; всё / '+fmt(c.mass_kg,1),fmt(c.cg_m[0],3)+' м'],['Вертикальное равновесие','ΣNᵢ = m(g + aZ)',fmt(c.mass_kg,1)+' × (9,81 + '+fmt(c.options.vertical)+')',fmt(c.target[0],1)+' Н'],['Перенос при торможении','ΔNперед = m aторм hCG / L',fmt(c.mass_kg,1)+' × '+fmt(c.options.brake)+' × '+fmt(c.cg_m[2],3)+' / 2,16',fmt(c.mass_kg*c.options.brake*c.cg_m[2]/2.16,1)+' Н'],['Момент при повороте','Σ(Nᵢ yᵢ) = mg yCG − m aY hCG',fmt(c.mass_kg,1)+' × ('+fmt(9.81+c.options.vertical)+' × '+fmt(c.cg_m[1],3)+' − '+fmt(c.options.lateral)+' × '+fmt(c.cg_m[2],3)+')',fmt(c.target[2],1)+' Н·м'],['Передняя жёсткость до шины','kF = kθ / l² + kдоп λ²',fmt(c.options.frontTorsion)+' / '+fmt(c.options.frontArm)+'² + '+fmt(c.options.frontCoil)+' × '+fmt(c.options.frontMotion)+'²',fmt(c.front_rate_before_tire/1000)+' кН/м'],['Задняя жёсткость до шины','kR = kпруж λ²',fmt(c.options.rearSpring)+' × '+fmt(c.options.rearMotion)+'²',fmt(c.rear_rate_before_tire/1000)+' кН/м'],['Совместность четырёх опор','Nᵢ = Nᵢ₀ + kᵢ(z + θxᵢ + φyᵢ); A q = b', 'A = Σ kᵢ [1,xᵢ,yᵢ]ᵀ[1,xᵢ,yᵢ]; b — требуемые сила и моменты минус исходные', 'Δz '+fmt(c.displacements[0]*1000,1)+' мм; θ '+fmt(c.displacements[1]*180/Math.PI,3)+'°; φ '+fmt(c.displacements[2]*180/Math.PI,3)+'°'],['Проверка равновесия','r = [ΣN−FZ, ΣNx−MX, ΣNy−MY]', 'Суммы посчитаны по четырём найденным реакциям',c.residuals.map(v=>fmt(v,6)).join(' / ')+' Н; Н·м; Н·м']];$('loadFormulas').replaceChildren();for(const [name,formula,sub,result]of cards){const card=el('article');card.className='formula-card';card.append(el('h3',name),el('code',formula),el('p','Подстановка: '+sub),el('strong',result));$('loadFormulas').append(card);}$('loadStatus').textContent=c.note;window.loadCalculation=c;
 }catch(e){$('loadStatus').textContent=e.message;}}
 document.querySelectorAll('[data-load-param]').forEach(e=>e.addEventListener('input',render));render();$('exportWheelLoads').onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({items,result:window.loadCalculation},null,2)],{type:'application/json'}));a.download='wheel-loads.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 for(const [id,n]of Object.entries(data.nodes)){const article=el('article');article.id='node-'+id;article.className='physics-node';article.append(el('h3',id+' · '+n.name),el('p',n.description),el('p',n.law),el('code',n.formula),el('p',n.limit));$('nodeLaws').append(article);}
 for(const n of Object.values(data.subnodes||{})){const article=el('article');article.id=n.anchor;article.className='physics-node';article.append(el('h3',n.owner+' · '+n.name),el('p',n.description),el('p',n.law),el('code',n.formula),el('p',n.limit));$('subnodeLaws').append(article);}
 if(location.hash){const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target){const details=target.closest('details');if(details)details.open=true;target.scrollIntoView();}}
 for(const text of data.limitations)$('simulationLimits').append(el('li',text));for(const s of data.sources){const li=el('li'),a=el('a',s.title);a.href=s.url;a.target='_blank';a.rel='noopener';li.append(a);$('physicsSources').append(li);}
}catch(e){$('loadStatus').textContent='Ошибка данных: '+e.message;}
